### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by prakhar1989** [prakhar1989/react-tags#1]
Use Jest - https://facebook.github.io/jest/docs/tutorial-react.html

**Comment by rnicholus** [comment]
I would suggest skipping jest. It's incredibly slow and tied to an ancient version of Node.js. Jest is really a terrible testing tool in general. Instead, I would suggest sticking with Jasmine and Karma. You can run tests headless using PhantomJS. The best approach is to create a Travis CI account, setup a config file, and have Travis run your tests on each push to GtiHub. I'm working on a blog post that explains all of this in the context of React - https://github.com/Widen/fullstack-react/issues/3.

**Comment by prakhar1989** [comment]
Great! Looking forward to the blog post!

**Comment by rnicholus** [comment]
At [Widen](http://widen.com), we are discussing working on unit tests for react-tags as part of an upcoming sprint. Of course, if we end up using react-tags and are able to work this into a sprint, we will contribute the unit tests back to our project in a pull request. Either way, this is the high-level work I see required on our end:

- [ ] Pull in devDependencies: Jasmine, Karma, and PhantomJS (along with associated peer dependencies)
- [ ] Update `scripts` in package.json to run automated unit tests using the tools above. Tests will be run with Karma against a PhantomJS browser, with tests written using Jasmine.
- [ ] Write some unit tests for each of the three modules: suggestions, tag, reactTags. Will probably need to pull in babel-plugin-rewire to mock out internal dependencies for each module.
- [ ] Setup Travis CI to auto-run these tests on each push to GitHub against Phantom and headless Firefox.

You will need to complete steps 1 and 2 on the [Travis CI Getting Started Guide](https://docs.travis-ci.com/user/getting-started/) in order for the last item above to be completed.

**Comment by prakhar1989** [comment]
Sounds good Ray! Let me know when you want to enable Travis CI integration. Thanks again to you and the folks at Widen for your contributions.

Greatly appreciate it :+1:
