### ISSUE TITLE
Draggability Options

### ISSUE THREAD

**Issue by dnusca** [prakhar1989/react-tags#10]
An option to disable draggability would be useful for different implementations.

**Comment by prakhar1989** [comment]
@dnusca If you provide an empty dragHandler, it should work fine. 

```javascript
handleDrag: function() {
  // do nothing
}

render: function() {
  <ReactTags ... handleDrag={this.handleDrag} />
}
```
Do you have any specific ideas about disabling drag?

**Comment by dnusca** [comment]
@prakhar1989 Sorry, I thought the move cursor was implemented in the component. That works perfect.

**Comment by prakhar1989** [comment]
No problem! :+1:
