### ISSUE TITLE
Custom tag separator (Space bar, comma or enter)

### ISSUE THREAD

**Issue by yarnball** [prakhar1989/react-tags#108]
Great work with this.

Is it possible to use the Space Bar, comma, and enter keys all as options to separate tag entries?

Thanks

**Comment by Radivarig** [comment]
Find out the [key codes](https://www.cambiaresearch.com/articles/15/javascript-char-codes-key-codes), then pass this as a prop `delimiters={[32, 188, 13] /*space, comma, enter*/}`

**Comment by lasfin** [comment]
Delimeters by char codes don't work well. In russian keyboards we have comma and one of cyrillic letters on the same buttons. So, if we will use 188 char code as delimeter, we will lose ability to enter any russian word with letter 'Б' in it.

**Comment by ankitrg** [comment]
I am trying it like this and it doesn't work:

```javascript
<ReactTags
                tags={this.props.emails}
                handleDelete={this.props.handleAlertEmailDelete}
                handleInputBlur={this.props.handleAlertEmailAddition}
                handleAddition={this.props.handleAlertEmailAddition}
                delimeters={[13, 32, 188] /*space, comma, enter*/}
                placeholder="Enter email separated by commas"
                classNames={{tagInputField: 'form-control'}}
              />
```

**Comment by mrdannael** [comment]
I suppose that PR #196 should resolve the problem with russian keyboards, rigth? Or am I wrong? :)
