### ISSUE TITLE
the tags input is autofocus.can you add a param to setting when don't need focus this input

### ISSUE THREAD

**Issue by qynAUGMN** [prakhar1989/react-tags#12]

**Comment by prakhar1989** [comment]
Hi, I've published a new version which makes this [configurable](https://github.com/prakhar1989/react-tags#autofocus). Also, the latest version of `ReactTags` has a breaking changes in the API (from 0.x.x version), so make sure you read the usage section carefully - https://github.com/prakhar1989/react-tags#usage
