### ISSUE TITLE
Example site does not work the same as example packaged in repo

### ISSUE THREAD

**Issue by specialunderwear** [prakhar1989/react-tags#120]
The index.html of the example site is a year old. it uses react 0.13.3.

The thing is, in that demo drag and drop is excellent, at all times the full set of items is displayed, and you see the dragged item move in the list while dragging.

If you run the example in this repo, that is not the case, the dragged item disappears from the list and dropping is very awkward. You can not see how the list will end up.

**Comment by prakhar1989** [comment]
Hey @specialunderwear, you can try out a more recent example on [WebpackBin](http://www.webpackbin.com/41DVgMvv-) which are linked to in the docs. Is the behavior what you expect?

**Comment by prakhar1989** [comment]
This has been fixed now, checkout the [demo here](http://prakhar1989.github.io/react-tags/example/).
