### ISSUE TITLE
Focus when removing tags

### ISSUE THREAD

**Issue by Wildhoney** [prakhar1989/react-tags#128]
Expectedly, when removing a tag the focus is transferred from the `input` to the close button. However, it'd be nice to optionally transfer the focus **back** to the `input` immediately, thus improving UX.

Any thoughts on the best way to implement something like this? Would it require a lib change?

**Comment by prakhar1989** [comment]
Hey Adam, not sure I understand you correctly. When I use my mouse to click on the `x` button, the focus doesn't change, but when I used <kbd>backspace</kbd>, I see that the focus remains on the input. Are you referring to something else?

**Comment by Wildhoney** [comment]
For me in Chrome 55.0.2883.95:

- [Navigate to the demo](http://www.webpackbin.com/EJdPySdLG);
- Focus on the `input` (by default);
- Enter a country
- Delete the country

**Expected:** Focus remains on the `input` node
**Actual:** Focus is transferred to the `x` and thus you need to click on the `input` again

**Comment by Wildhoney** [comment]
![Focus](http://i.imgur.com/gyzdm2O.gif)

**Comment by prakhar1989** [comment]
Hey Adam, apologies for the late update - i just released a fix for this. Feel free to reopen the issue if it still persists.
