### ISSUE TITLE
handleFilterSuggestions breaks drop down suggestions click handlers

### ISSUE THREAD

**Issue by brianarpie** [prakhar1989/react-tags#129]
Hi, when I include `handleFilterSuggestions` and return the array of suggestions without modification, it does what you would expect: all `suggestions` populate the drop down list. However, when i click any of the suggestions, they all do the same thing: call `handleAddition` with the first element from the `possibleSuggestionsArray`. Am i missing something here ? All of the click handlers are passing the first element of the array to `handleAddition`. If I remove `handleFilterSuggestions` the problem is fixed. 

Here's the basic shape of what I'm talking about:

```

handleAddition(tag) {
    // tag always equals the first element in possibleSuggestionsArray
}

handleFilterSuggestions(textInputValue, possibleSuggestionsArray) {
    // possibleSuggestionsArray is what you would expect
    return possibleSuggestionsArray;
}

...

<ReactTags 
    handleFilterSuggestions={this.handleFilterSuggestions} />
```

**Comment by indapublic** [comment]
@brianarpie Do you still have your behaviour? I cannot reproduce it

**Comment by mrdannael** [comment]
@brianarpie do you still have your behaviour? :)

**Comment by blakeyc** [comment]
For anyone else who happens to run into this issue, the fix I found was to disable the autocomplete. 

Looks like the if statement is causing the issue: https://github.com/react-tags/react-tags/blob/4cd4f6519a51b3d0b17b40ccf5d12ff85e9d24e6/src/components/ReactTags.js#L383
