### ISSUE TITLE
demo page gives me 404

### ISSUE THREAD

**Issue by Voxis** [prakhar1989/react-tags#139]
funky 404 though.

**Comment by prakhar1989** [comment]
Thanks for making the issue - just updated the URL.

**Comment by cmackay** [comment]
I just tried the demo page and it shows 404. https://prakhar.me/react-tags/example

**Comment by prakhar1989** [comment]
Fixed the link. Here it is http://prakhar1989.github.io/react-tags/example/

**Comment by cmackay** [comment]
Great, Thanks!
