### ISSUE TITLE
Async suggestions

### ISSUE THREAD

**Issue by brigand** [prakhar1989/react-tags#14]
Use case: tag suggestions based on (potentially thousands of) tags used elsewhere.

I'm going to fork and implement this, is a PR for this acceptable? Is this api good?

```js
<ReactTags
  tags={tags}
  suggestions={this.state.loading ? this.state.suggestions : []}

  loading={this.state.loading}
  loadingMessage="Loading..."
  onIncompleteInput={(text) => undefined}
  />
```

If `loading` is truthy, display an additional item at the end of the suggestions with the loading class.

Additional classes: 

 - `ReactTags__tagInput--loading`
  - use case: spinner on right side of input
 - `ReactTags__suggestions--loading` 
  - use case: change background color, etc.
 - `ReactTags__loading-indicator`
  - use case: style the loadingMessage (could be an icon or whatever).

**Comment by prakhar1989** [comment]
@brigand: Looks good and I'm definitely up for accepting the PR. Quick note about the API.. what does the `onIncomepleteInput` prop required for?

**Comment by brigand** [comment]
It gives you a place to start requests to the server.

```js
onIncompleteInput={
  (text) => ajaxAutocomplete(text).then((suggestions) => this.setState({suggestions})
}

**Comment by prakhar1989** [comment]
Right. Makes sense. :+1:

**Comment by checkhavoc** [comment]
It seems like this type of request can be handled in the PR I created for #19 @brigand

**Comment by prakhar1989** [comment]
Thanks @checkhavoc for your work on this! Closing this issue.

**Comment by yifeikong** [comment]
> It gives you a place to start requests to the server.
> 
> ```js
> onIncompleteInput={
>   (text) => ajaxAutocomplete(text).then((suggestions) => this.setState({suggestions})
> }
> ```

This should be in the documentatioin.
