### ISSUE TITLE
Tiny issue: Demo link kind of broken

### ISSUE THREAD

**Issue by chrisssycollins** [prakhar1989/react-tags#142]
The current link takes you [here](https://www.webpackbin.com/41DVgMvv-) and asks to notify the author about moving their BIN to the new version of Webpackbin. 

![screen shot 2017-03-07 at 09 32 35](https://cloud.githubusercontent.com/assets/6320793/23650162/16b3284a-0319-11e7-86f9-40b8c0fd78e5.png)

The old version can be used but not sure how long for.

**Comment by prakhar1989** [comment]
Thanks - just pushed an update!
