### ISSUE TITLE
Unspecified props are swallowed

### ISSUE THREAD

**Issue by cklab** [prakhar1989/react-tags#144]
I'm using react-tags alongside [react-bootstrap](https://react-bootstrap.github.io/). One of the components I use from there is `OverlayTrigger`, which throws on various handlers and events on the child component: `onMouseOut` and `onMouseOver` to name a few. But because the props that are passed to `ReactTags` are [selectively extracted](https://github.com/prakhar1989/react-tags/blob/master/lib/ReactTags.js#L272-L279), these handlers are lost.

So in the following example, the intended behavior would be to display a popover (tooltip) `onMouseOver` -- `onMouseOver` is not transferred to any DOM element, so we get nothing.

```
render: function() {
        let tooltip = (
            <Popover title="Title" id="popover">
                Tee-hee
            </Popover>
        );
        return (
            <OverlayTrigger placement="top" key="tooltip" overlay={tooltip}>
                <ReactTags/>
            </OverlayTrigger>
        );
}
``` 

Would you open to spreading the rest of the props on one of the components? I'll open a PR with my proposed changes and we can discuss further if it would be a viable solution.

**Comment by mrdannael** [comment]
#145

**Comment by cklab** [comment]
@mrdannael thanks for adding the ref, I can rebase if the PR is good-as-is.

**Comment by mrdannael** [comment]
Yes, please. Rebase with master :)

**Comment by cklab** [comment]
One way or another, something like it would be necessary to avoid the "unknown prop" warnings. Without it, props such as `handleDelete`, `handleAddition`, etc. would be passed to the top-level div leading to those warnings.
