### ISSUE TITLE
Tags Validation

### ISSUE THREAD

**Issue by pola88** [prakhar1989/react-tags#15]
Hi guys!

is there a way to validate the tag that the user wants to add?

Thanks,

**Comment by prakhar1989** [comment]
Hi @pola88 

Yup, you can surely validate the tag - 

```javascript 
handleAddition: function(tag) {
        var tags = this.state.tags;
        
        // sample validation
        if (tag.length <= 2) {
            return; // do nothing
        }
       
        tags.push({
            id: tags.length + 1,
            text: tag
        });
        this.setState({tags: tags});
},
```

**Comment by prakhar1989** [comment]
Hi @pola88,

Since I haven't heard back I'm assuming this is working for you now. I'm closing this issue for now - if you face any issues feel free to re-open this.

Thanks!
