### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by prakhar1989** [prakhar1989/react-tags#197]
As evidenced by the growing number of issues and PRs on this project, I've not been able to keep up with growing and maintaining this library. I'm quite occupied with other projects at the moment and do not see myself freeing up to work on this library in the foreseeable future.

Instead of letting it languish, I was hoping if someone would be interested in maintaining this library and working with the community. You'll be added as a project collaborator and will have full freedom to take the library in any direction that you want. 

If any of this sounds interesting, drop me an email (which is on my profile) and we can take this forward.

Thanks for showing interest!

**Comment by gopikishanm** [comment]
Hi Prakhar,

I will try to maintain this library and will help with coding. Please let me know what are expected from me so that I can understand the role better.

**Comment by mrdannael** [comment]
Hi Prakhar,

I'm interested in maintaining react-tags. I sent you an email.

**Comment by dehlen** [comment]
any news here ? There are a lot of unmerged open PR's and I am wondering whether there will be a maintainer in the future or if I should work with a fork of myself.

**Comment by prakhar1989** [comment]
Sorry, no news yet. Haven't heard back on the follow ups yet. Let me know if you are interested!

**Comment by mrdannael** [comment]
@dehlen Is there something you are waiting for in particular? :)

**Comment by prakhar1989** [comment]
Just an update: Daniel (mrdannael) has volunteered to be a maintainer of this library going forward! Thank you very much Daniel! 🎉

**Comment by Rafi993** [comment]
@prakhar1989  why not merge this project with https://github.com/olahol/react-tagsinput
