### ISSUE TITLE
Making drag an drop optional?

### ISSUE THREAD

**Issue by ajmas** [prakhar1989/react-tags#198]
I came by this project by means of react-tags-autocomplete (i-robots-fork), which removes drag and drop. I also made some PR to that project to deal with adding support for internationalisation. 

Given this background, would it be worth making drag and drop optional for people who aren't interested in the support, as a way of possibly merging efforts down the road?

**Comment by ad1992** [comment]
@ajmas I am not sure if we will be working on this immediately but I would be happy to review a PR on this feature. Please feel free to pick this up.

**Comment by ad1992** [comment]
@ajmas this feature has been pushed. I will release a version soon.
