### ISSUE TITLE
react 16?

### ISSUE THREAD

**Issue by davidmfoley** [prakhar1989/react-tags#217]
On github, it looks like v4.7.1 includes react & react-dom v16.0.0 as peerDependencies.

However, when I install latest from the npm registry, I get v4.7.2, published 7 months ago, with versions 14 and 15 of react and react-dom in the peerDependencies.

**Comment by mrdannael** [comment]
The latest version of react-tags is 4.7.3 now. Update me if this still occurs.

**Comment by Dictory** [comment]
@mrdannael Hello. I have that error:
`Component DropTarget(DragSource(Tag)) declared PropTypes instead of propTypes. Did you misspell the property assignment?` when use react-tags. 
just for notice

**Comment by mrdannael** [comment]
@Dictory I can't replicate the issue. Can you use jsfiddle or something similar to reproduce it?

**Comment by ad1992** [comment]
@Dictory does the issue still occur ?  we have migrated to react 16 in latest version 4.9.1

**Comment by Dictory** [comment]
@ad1992 sorry, now i doesn\`t have error

**Comment by ad1992** [comment]
awesome 👍 closing this issue
