### ISSUE TITLE
why are you modifying state directly?

### ISSUE THREAD

**Issue by ghost** [prakhar1989/react-tags#220]
In this sample

```

    handleDelete(i) {
        let tags = this.state.tags;
        tags.splice(i, 1);
        this.setState({tags: tags});
    }

```

why are you modifying state directly? one is not allowed to do so according to react doc

**Comment by ronalfy** [comment]
Modifying state directly is like going `this.state.tags=tags`. I believe the example to be correct.

**Comment by dpkshrma** [comment]
`splice` mutates the variable acted upon. So, the issue is valid.
It is easy to do it immutably using `slice` or `filter` though:
```js
// using slice
handleDelete(i) {
  const { tags } = this.state;
  this.setState({
    tags: tags.slice(0, i).concat(tags.slice(i+1))
  });
}
// using filter
handleDelete(i) {
  const { tags } = this.state;
  this.setState({
    tags: tags.filter((tag, idx) => idx !== i)
  });
}
```

**Comment by ad1992** [comment]
this has been fixed in the code @ronalfy @dpkshrma.
