### ISSUE TITLE
Pass tag properties to removeComponent

### ISSUE THREAD

**Issue by LukaszNowakPL** [prakhar1989/react-tags#224]
I use removeComponent to show nice delete button. Sometimes I don't want to delete certain Tag - just make button disabled. I might be able to do this if Tag properties pass to my removeComponent.

**Comment by mrdannael** [comment]
Will this [PR](https://github.com/prakhar1989/react-tags/pull/202) be enough for you? :)

**Comment by mrdannael** [comment]
Merged. Closing this issue.
