### ISSUE TITLE
["react": "^16.0.0"] Warning: Component DragDropContext(ReactTags) declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?

### ISSUE THREAD

**Issue by JuliaPetrishina** [prakhar1989/react-tags#225]
## Steps to reproduce

1. Install React 16.0.
2. In Chrome (or probably any other browser), open the dev console on the page with react-tags
3. As soon as the page contain react-tags React shows the following:
_Warning: Component Menu declared ``PropTypes`` instead of ``propTypes``. Did you misspell the property assignment?_

**Comment by drewcook** [comment]
Yes I was going to create this same issue.  This is definitely a warning that comes up after updating to React 16.  This can be fixed by updating line 340 on https://github.com/prakhar1989/react-tags/blob/master/lib/ReactTags.js

**Comment by drewcook** [comment]
I was poking around and looks like there is already a pull request made for this issue.  Hopefully its handled soon. https://github.com/prakhar1989/react-tags/pull/222

**Comment by prakhar1989** [comment]
#222 has been merged. Will release an update soon.
