### ISSUE TITLE
Show data fetched from server

### ISSUE THREAD

**Issue by ashfaqrafi** [prakhar1989/react-tags#232]
In my project I need to show some predefined tags fetched from the server using network call, the user input will be taken along with the fetched tags and new array of tags will be sent to the server using PUT request. How can I get the data fetched from the server and show in the tags?
Here is my code so far:
```
constructor(props){
    super(props);
    this.handleSubmit = this.handleSubmit.bind(this);
    this.state = {
      tags: [ ],
    };
      this.handleDelete = this.handleDelete.bind(this);
      this.handleAddition = this.handleAddition.bind(this);
  }
handleDelete(i){
        const tags = this.state.tags;
        tags.splice(i, 1);
        this.setState({tags});
    }

    handleAddition(tag){
        const tags = this.state.tags;
        tags.push({
            id: tags.id,
            text: tag
        });
        this.setState({tags});
    }
fieldData(){
      const fields = Object.assign(this.props.synonym.table_fields).map(h => ({
          id: h.id,
          synonyms: this.state.tags
      }));
      return{
          fields,
          table_id: this.props.synonym.selectedTable.id,
      }
  }

  handleSubmit(e){
    e.preventDefault();
    this.props
      .tableData(this.fieldData())
      .then((res) => {
        swal({
          title: 'Synonym data is sent to the server',
          icon: 'success'
        });
      })
      .catch((error) => {
        // eslint-disable-next-line no-console
        console.error('Synonym Updating failed: ', error.response.data);
        swal({
          title: 'Error sending synonym data',
          icon: 'error'
        });
      });
  }

  tableRender(){
    const placeholder = 'Write a synonym and hit enter';
    const { tags } = this.state;
    if (!this.props.synonym.selectedTable) return;
    const Fields = this.props.synonym.table_fields;
    return Object.assign(Fields).map(t =>
        <tr key={t.id}>
          <td className="font-18 synonym-font-col width-14p"><input type="number" className="border-none" id="field_id" value={t.id} readOnly /></td>
          <td className="font-18 synonym-font-col width-14p">{t.name}</td>
          <td className="width-14p font-18 synonym-font-col"> {t.alias}</td>
          <td>
            <div className="resize_this">
                   <ReactTags
                              placeholder={placeholder}
                              tags={tags}
                              handleDelete={this.handleDelete}
                              handleAddition={this.handleAddition}
                   /> 
             </div>
          </td>
        </tr>
    );
  }
```
@prakhar1989 need help badly.

**Comment by mrdannael** [comment]
The easiest way imo is to fetch tags from backend at the very beginning of mounting component i.e. and just put them in `tags` state.

Also could you please format your code for better readability? :)

**Comment by ashfaqrafi** [comment]
Thanks for the response, could you please elaborately tell me where to change things in my code block? @mrdannael

**Comment by mrdannael** [comment]
[Axios](https://github.com/axios/axios) package should be enough for that. Let's assume that you have endpoint for fetching tags from backend i.e. `/api/tags`. So we want to make api call in `componentDidMount()` and update our state.

```javascript
componentDidMount() {
   axios.get('/api/tags')
      .then(resp => this.setState({ tags: resp.data.tags }))
      .catch(err => { console.log(err) }) // handle error properly
}
```

Response from backend should look like this:
```js
{
   tags: [{
      id: 1,
      text: 'Tag 1'
   }, {
      id: 2,
      text: 'Tag 2'
   }]
}
```

Hope it helps :)

**Comment by ashfaqrafi** [comment]
Thanks, I am trying it now.

**Comment by ashfaqrafi** [comment]
Hi @mrdannael is there any way I can save these tags data in redux store instead of fetching them from setting state as in the same component I am showing data using redux store like tableid, tablename, ailas and then there is tags for individual rows of the table, now I am facing problem getting the tags using state as my other table components of the same table are loaded from redux store.

**Comment by mrdannael** [comment]
I see two options for it now @ashfaqrafi:
1. Create simple action that will put your tags into specific reducer and then just call `this.props.dispatch` with that action and proper arguments i.e. `response.data.tags`. (or refer to [this](https://redux.js.org/docs/basics/UsageWithReact.html))
2. Create action/function with [redux-thunk](https://github.com/gaearon/redux-thunk). Inside it just make an api call and inside `then()` call dispatch where you will put payload into specific reducer (similar to 1 option).

I'm closing this issue because it's not related strictly to react-tags itself.
Please see the rest of docs for React, [Redux](https://redux.js.org/) and/or redux-thunk.
Also look for answers on StackOverflow too :)

Cheers!

**Comment by ashfaqrafi** [comment]
Thanks @mrdannael :)
