### ISSUE TITLE
Cannot read property 'stopPropagation' of undefined

### ISSUE THREAD

**Issue by InonHold** [prakhar1989/react-tags#234]
After upgrading to latest version (4.8.0) I started getting the following error:
'Cannot read property 'stopPropagation' of undefined'
when removing a tag using keyboard's backspace.

Looking into the code it seems like - handleDelete(i, e) is not getting the 'e' argument when it is called from handleKeyDown.

**Comment by mrdannael** [comment]
Should be fixed in v4.8.1.

Released! Try it now :)

**Comment by InonHold** [comment]
Thanks for the quick fix
👍
