### ISSUE TITLE
Duplicate tags | You can enter the same tag twice

### ISSUE THREAD

**Issue by joshpitzalis** [prakhar1989/react-tags#235]

**Comment by joshpitzalis** [comment]
Is this deliberate? Is there any reason why people would want to do this or is this a bug to be fixed?

**Comment by mrdannael** [comment]
Looks like it's a bug to be fixed.

**Comment by ad1992** [comment]
@mrdannael can I take this up ?

**Comment by mrdannael** [comment]
Should be fine now. Closing :)

**Comment by gskrap** [comment]
your "fix" broke the ability to set anything other than plain text as the "text" attribute for a tag.

for a simple example example,  
{id: 1, text: <span title="here's a tool tip">you can hover on me</span>}
used to be a valid tag

this functionality of passing html elements as the value of the text attribute provided lots of flexibility. please undo this.

**Comment by gskrap** [comment]
please see my newly opened issue https://github.com/prakhar1989/react-tags/issues/267
