### ISSUE TITLE
Add Release

### ISSUE THREAD

**Issue by jkusachi** [prakhar1989/react-tags#24]
Since Github supports releases, I think it would be good to add them for this repo

Currently releases tab is like the following, even though npm states its 1.0.3 (latest of 11 releases):

![screenshot 2015-11-05 11 25 12](https://cloud.githubusercontent.com/assets/332474/10979212/032ae78e-83b0-11e5-93a0-21fe38f545ea.png)

**Comment by prakhar1989** [comment]
Thanks @jkusachi, that's a nice idea  :+1: . I'll definitely add the subsequent releases on Github as well.

**Comment by prakhar1989** [comment]
Added a release for `2.0.1` - https://github.com/prakhar1989/react-tags/releases/tag/v2.0.1. Thanks again for raising the issue!
