### ISSUE TITLE
Add option to maintain suggestion list open for development purposes

### ISSUE THREAD

**Issue by bepbrasil** [prakhar1989/react-tags#241]
For some reason, the suggestion list always closes now, if your click enter, if you right click the suggestion list, if you right click the input field. Something has changed on the latest release because this wasn't happening.

This is not really a bug, so I'm suggesting a new option so the suggestion list stays open because this helps us to stylize the component using the browser developer tools. Now anything I do makes the suggestion list disappear and the elements are removed from the DOM, so it's really harder to debug the CSS.

Thanks

**Comment by mrdannael** [comment]
Thanks for the info. I'll look on it today.

**Comment by sudheeshcm** [comment]
@bepbrasil and for others in search for this option,
```
<ReactTags
     tags={tags}
     shouldRenderSuggestions={() => true}
/>

```

This should solve the problem.
