### ISSUE TITLE
tags are overlapping 

### ISSUE THREAD

**Issue by jadelmir** [prakhar1989/react-tags#242]
![screen shot 2018-03-05 at 4 50 37 pm](https://user-images.githubusercontent.com/31207632/36981279-67a279a0-2095-11e8-9336-22ccf5fd9f90.png)

					<div className="element">
						<div className="inputCountries">
							<Label
								htmlFor="hf-email"
								style={{
									fontSize: 20
								}}
							>
								{item}
							</Label>
						</div>

						<div>
							<ReactTags
								tags={tags}
								suggestions={suggestions}
								handleDelete={this.handleDelete}
								handleAddition={this.handleAddition}
								handleDrag={this.handleDrag}
							/>
						</div>

						<div className="inputCountries">
							<Input
								type="select"
								placeholder={item}
								data-key={item}
								defaultValue={items[item]}
								onChange={this.handleEditChange}
							>
								{dropdown}
							</Input>
						</div>

					</div>

and I have user display flex for adjustments

**Comment by ameenmattar** [comment]
Same Issue here.

**Comment by mrdannael** [comment]
Are you using styles provided by library?
