### ISSUE TITLE
Added empty tag if press 'Arrow down' and press 'Enter'

### ISSUE THREAD

**Issue by ndemidovich-sc** [prakhar1989/react-tags#243]
### Steps to reproduce
1. Set focus on input.
2. Type text 'test' in field
3. Press `arrow down`
4. Press `enter`

### Expected result
Tag with text 'test' is displayed

### Actual result
![capture](https://user-images.githubusercontent.com/25152982/37034015-f153a8e0-2158-11e8-8418-f738eb5f93c3.PNG)

**Comment by ad1992** [comment]
@mrdannael I will look into this.

**Comment by mrdannael** [comment]
Awesome!
