### ISSUE TITLE
After removing any tag, the next tag is overlapped by the last tag in the array

### ISSUE THREAD

**Issue by Komar0ff** [prakhar1989/react-tags#244]
on http://prakhar1989.github.io/react-tags/example/
![gif](https://user-images.githubusercontent.com/10588170/37042735-1f9cd98a-2170-11e8-904a-e37adddf3c22.gif)

**Comment by mrdannael** [comment]
Oh, key props in tags are duplicated. Workin' on in :)

**Comment by mrdannael** [comment]
Ok. So the problem is not library itself but proper handling addition method. Need to fix example page then :)
