### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by bzums** [prakhar1989/react-tags#25]
When I try to run the example with react 0.14 I get the following error:
```Warning: DragDropContext(ReactTags)(...): React component classes must extend React.Component.```
```Uncaught Error: Invariant Violation: DragDropContext(ReactTags).render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.```

Am I missing a point?

Best

**Comment by bzums** [comment]
Maybe some additional info: I copied the example from the readme.md into my project and imported ReactTags like the following:

```import { WithOutContext as ReactTags } from 'react-tag-input';```

**Comment by prakhar1989** [comment]
@bzums Let me have a look at this and get back to you.

**Comment by superafroman** [comment]
I think this is caused by using react@0.14.  It might be worth merging this fork, https://github.com/picryl/react-tags, which has updated and seems to be working.

**Comment by bzums** [comment]
Is it working for you? It looks like I get the exact same error with the given fork.

**Comment by superafroman** [comment]
Yeah it's working for me.  How did you install it?  I had to clear react-tag-input from node_modules and my package.json and then install the fork directly from github - `npm install --save git://git@github.com:picryl/react-tags.git`.  And obviously rebuild my project.  If you have react-dnd installed as well it may be worth removing that before installing the fork.

**Comment by xonev** [comment]
I'm having the same issue and the fork appears to fix it.

**Comment by not-raspberry** [comment]
The problem is the Github version is 2.0.1 while the one available on NPM is still 1.0.3.

**Comment by prakhar1989** [comment]
Hi everyone, I just pushed the latest release on NPM. Can someone try and let me know if it works as expected? Thanks!
