### ISSUE TITLE
Documenting option defaults

### ISSUE THREAD

**Issue by levininja** [prakhar1989/react-tags#257]
The documentation at https://www.npmjs.com/package/react-tag-input is great at documenting what all the options are.

However it would be really useful if it also documented what the defaults are for each optional option (i.e. if the user doesn't specify it, what is the default behavior?).

**Comment by ad1992** [comment]
@levininja sure will add the defaults in the documentation.

**Comment by ad1992** [comment]
@levininja sorry I didn't get time to work on this. Would you like to give a PR on this ?, I would be happy to review :)
