### ISSUE TITLE
allowUnique

### ISSUE THREAD

**Issue by ad1992** [prakhar1989/react-tags#258]
allowUnique will decide whether the tags will be duplicated. 

Currently the suggestions also shows the options which are already added so clicking on that, the user won't be be able to add the option as tag as https://github.com/prakhar1989/react-tags/pull/245 got pushed. This will also be solved with this prop.

This prop will help in deciding whether to allow only unique tags.

cc @mrdannael @prakhar1989

**Comment by prakhar1989** [comment]
Is there a usecase for having duplicated tags? If not, I think having the unique only behavior sounds reasonable to me.

**Comment by ad1992** [comment]
@prakhar1989 @mrdannael some time back when I wanted to use react-tags in one of my project where I did need the flexibility to decide whether tags should be duplicated or not.

My use case was I wanted to receive the input of test cases for a particular coding challenge, the test cases if includes array then it can have input as [1,2,3,2,1] or ['abc','def','abc']. It also needed to allow empty string. We can think later if allowing empty string should be made as prop.
People might have such usecases so wanted to add one prop which decides to whether to allow duplicate tags. by default the behaviour will be only unique tags will be allowed as you said, but if user wants more control over it then he can make use of this prop. Does this make sense ?

**Comment by prakhar1989** [comment]
Ah okay. Sounds good then!

**Comment by gskrap** [comment]
handling duplicates should be handled by the developer on the passed handleAddition function for maximum flexibility.

checking tag.text equality by calling .toLowerCase is restricting the text attr to be plain text, please see my open issue https://github.com/prakhar1989/react-tags/issues/267

**Comment by Fahdshehzad** [comment]
+1
