### ISSUE TITLE
Different type of tags

### ISSUE THREAD

**Issue by rozekfr** [prakhar1989/react-tags#259]
Is it possible to render two different tag for example blue and red one? Is it possible to add class to tag or something like that?

**Comment by ad1992** [comment]
@rozekfr you can pass classNames as a prop to your component for custom styling. Please check https://github.com/prakhar1989/react-tags/issues/258. Does this help you ?

**Comment by rozekfr** [comment]
This is not what I want. I need to add two classes for tag. I want to display one type of tag with blue background and another type of tag with red background.

**Comment by ad1992** [comment]
ahh ok I get it now @rozekfr . In that case a prop classname needs to be passed to each tag. Would you be interested in giving a PR for this feature ?

**Comment by rozekfr** [comment]
Sure, when I will have some extra time I will do that. I have an idea, how to do that.

**Comment by ad1992** [comment]
Awesome. looking forward for your PR :)
