### ISSUE TITLE
preventing duplicate tags breaks the ability to pass html as the text attr for tags

### ISSUE THREAD

**Issue by gskrap** [prakhar1989/react-tags#267]
your fix of preventing duplicate tags broke the ability to set anything other than plain text as the "text" attribute for a tag.

for a simple example,
```{id: 1, text: <span title="hi i'm a tool tip">you can hover on me</span>}```
used to be a valid tag

this functionality of passing html elements as the value of the text attribute provided lots of flexibility. 

preventing duplicates is very easy to implement in the passed handleAddition function.

**Comment by ad1992** [comment]
@gskrap I will look into this.
