### ISSUE TITLE
Error while dragging tags: Unable to find node on an unmounted component.

### ISSUE THREAD

**Issue by odalysadam** [prakhar1989/react-tags#269]
Today I installed 4.9.1 using yarn and when dragging tags the following error occured:

```
invariant.js:42 Uncaught Error: Unable to find node on an unmounted component.
   at invariant (invariant.js:42)
   at findDOMNode (react-dom.development.js:15280)
   at Object.hover (Tag.js:51)
   at Target.hover (createTargetFactory.js:71)
   at DragDropManager.hover (dragDrop.js:139)
   at Object.eval [as hover] (DragDropManager.js:92)
   at HTML5Backend.handleTopDragEnter (HTML5Backend.js:519)
invariant    @    invariant.js:42
findDOMNode    @    react-dom.development.js:15280
hover    @    Tag.js:51
hover    @    createTargetFactory.js:71
hover    @    dragDrop.js:139
(anonymous)    @    DragDropManager.js:92
handleTopDragEnter    @    HTML5Backend.js:519
```

I rolled back to 4.7.3 (the version I was working with) and it's working just fine again. This is my first issue ever so I don't know what is expected when reporting a bug. Feel free to ask questions and I will try to give answers. I'm relatively new to React and Webpack, so I don't really have a clue what's going wrong here. Just wanted to put this here in case anybody else as clueless as me encounters the same thing. Maybe you know what's going wrong. :)

**Comment by ad1992** [comment]
@odalysadam which browser are you using ?

**Comment by odalysadam** [comment]
@ad1992 Google Chrome Version 65.0.3325.181 and Firefox Quantum 58.0.2 used on a MacBook

**Comment by ad1992** [comment]
@odalysadam does this happen here http://prakhar1989.github.io/react-tags/example/

**Comment by odalysadam** [comment]
@ad1992 nope, it does not :)

**Comment by dragoscacuci** [comment]
@odalysadam Make sure the React version used by your application is at least the same as the version used by react-tag-input.
