### ISSUE TITLE
Wrong code in v5.0.0 dist

### ISSUE THREAD

**Issue by gjvoosten** [prakhar1989/react-tags#287]
It appears the `dist-modules` are not up-to-date w.r.t. the `lib` code, compare e.g.:

https://github.com/prakhar1989/react-tags/blob/v5.0.0/lib/ReactTags.js#L62

with:

https://github.com/prakhar1989/react-tags/blob/v5.0.0/dist-modules/ReactTags.js#L136

The dist still refers to `item.toLowerCase()` whereas the lib refers to `item.text.toLowerCase()`…

**Comment by ad1992** [comment]
@gjvoosten thanks a lot for reporting this.Its fixed now https://github.com/prakhar1989/react-tags/blob/v5.0.1/dist-modules/ReactTags.js#L136

**Comment by gjvoosten** [comment]
@ad1992 Thanks for fix and the quick turn-around time!
