### ISSUE TITLE
Error on IE11: Object doesn't support property or method 'isInteger'

### ISSUE THREAD

**Issue by dcsaszar** [prakhar1989/react-tags#293]
* Use IE11
* Open https://react-tag-input.stackblitz.io/

### Expected

Demo works

### Actual

Shows a blank page.
Browser console:

`Object doesn't support property or method 'isInteger'`

**Comment by dcsaszar** [comment]
According to #277 this should already be fixed 🤷‍♂️

**Comment by ad1992** [comment]
@dcsaszar the stackblitz seems to use v4.8.1 thats you are getting this bug. Thanks for reporting this. We will update the stackblitz dependencies.

**Comment by ad1992** [comment]
@dcsaszar this is fixed
