### ISSUE TITLE
Displaying tags below input field

### ISSUE THREAD

**Issue by mikailbayram** [prakhar1989/react-tags#297]
Is there a way of displaying the tags below the input field instead of above it?

**Comment by ad1992** [comment]
@mikailbayram we don't have any way to display the tags below the input field. Would be happy to receive a PR for the same :)

**Comment by tabrath** [comment]
@ad1992 I'm eager to do this, but what would be a good prop to specify this? `over`, `under`, `before` or  `after` maybe?

**Comment by ad1992** [comment]
@tabrath I think we should instead add a prop `inputFieldPosition` which has default value `inline` and optional value `below` and `above` . WDYT ?

**Comment by tabrath** [comment]
@ad1992 Sure, sounds good. Keeping the `inline` prop for backwards compatiblity?

**Comment by ad1992** [comment]
@tabrath yes lets keep `inline` prop in `5.x.x` for backward compatibility. Can you add a `TODO Comment` that it will be removed in version `6.x.x` ? And also add in read me as well that we will remove in version `6.x.x`.

**Comment by atiqueansari1987** [comment]
can I take this?

**Comment by tabrath** [comment]
@atiqueansari1987 yes!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by atiqueansari1987** [comment]
@tabrath @ad1992 I am not able to run the project locally. Running npm start is starting the webpack dev server but accessing http://localhost:8090/ is listing directory. Can you help me with this?
