### ISSUE TITLE
A problem with delimeters

### ISSUE THREAD

**Issue by ibrahimshaer** [prakhar1989/react-tags#300]
Pasting into the input field of react tags automatically adds the tag to the list of selected tags.

**Comment by ad1992** [comment]
Can you explain more what you mean and may be provide an example as well ?

**Comment by ibrahimshaer** [comment]
Hello,
When the user is pasting in the input of the react tags, reacts tags handle
Addition prop is triggered without triggering input handling prop.

Best Regards,
Ibrahim Shaer.

**Comment by ad1992** [comment]
@ibrahimshaer this should be fixed now. can you check in the latest release v5.0.2

**Comment by ibrahimshaer** [comment]
Thank you.
