### ISSUE TITLE
Weird looking 

### ISSUE THREAD

**Issue by sandropoluan** [prakhar1989/react-tags#307]
I got weird looking component. What I miss?

![weird](https://user-images.githubusercontent.com/11922251/39303348-61fae1c4-4988-11e8-89dd-88e89a9bbb08.png)

**Comment by ad1992** [comment]
Can you please share the props you passed to the component ?

**Comment by sandropoluan** [comment]
```
<ReactTags
            tags={[]}
            inline
            placeholder="Tambahkan kantor"
            suggestions={[]}
            handleDelete={i => {
              console.log(i)
            }}
            handleAddition={tag => {
               console.log(tagi)
            }}
            handleDrag={() => {}}
          />
```

**Comment by ad1992** [comment]
I agree @sandropoluan . The CSS should be added by default. We should bundle the css in webpack. Thanks for reporting this bug.
