### ISSUE TITLE
Bump version to 5.0.2 and release with fixes to paste

### ISSUE THREAD

**Issue by jpbufe3** [prakhar1989/react-tags#312]
Now that #306 is merged with master, bump the appropriate version numbers to 5.0.2 and create a release to deploy to npm.
@ad1992 - let me know if there's anything I can do here, but figured it might be easiest for you to just handle. Thanks!

**Comment by ad1992** [comment]
@jpbufe3 I will release it by tomorrow. Some pending cleanup needs to be done and some pr needs to be merged before I make the release.

**Comment by ad1992** [comment]
released 5.0.2
