### ISSUE TITLE
Getting a `Cannot read property isInteger of undefined` all of a sudden

### ISSUE THREAD

**Issue by ebrillhart** [prakhar1989/react-tags#318]
Hi!

I've been using this library in a project for a few months now and it's worked great. I upgraded to the latest version a few days ago though, and I'm now getting a `Cannot read property isInteger of undefined` error in the browser, to the point that the browser crashes. It looks like the `Number` library isn't getting imported correctly from core-js in some way in the `suggestions.js` file - it's failing in the `shouldRenderSuggestions` method. I'm going to bump back to an earlier version for now, but would love a fix for this. Thanks!

**Comment by ebrillhart** [comment]
closing - resolved

**Comment by ad1992** [comment]
@ebrillhart what was the issue and how was it resolved ?

**Comment by ebrillhart** [comment]
it was an internal project dependency issue!
