### ISSUE TITLE
Why suggestion only appear when I type two or more letters ?

### ISSUE THREAD

**Issue by AChaoZJU** [prakhar1989/react-tags#319]
This problem is found in the [example](https://stackblitz.com/edit/react-tag-input-1nelrc?file=index.js) of this repository. 
If I type one letter,  for example, `L`. There is no suggestions. If I type `La`, `Laos` and `Lativa` will appear in the suggestions. 
It seems that [index.js](https://stackblitz.com/edit/react-tag-input-1nelrc?file=index.js) don't explain the problem.

**Comment by ad1992** [comment]
@AChaoZJU you can pass `minQueryLength` as `1` and it will start rendering suggestions for 1 letter. By default `minQueryLength` is 2.
