### ISSUE TITLE
I cannot get separate values for two or more react-tag inputs.

### ISSUE THREAD

**Issue by rkterungwa16** [prakhar1989/react-tags#325]
For my current use case, I have an input for `included keywords` and another for `excluded keywords`, for which I need to collect separate tag values. Whenever I create a tag for one of the input fields, and click on enter, the tag appears on the other input field. Is there a way to do get these values separately currently.

**Comment by ad1992** [comment]
@rkterungwa16 can you give an example what you mean so its more clear ? I didn't get this line ` Whenever I create a tag for one of the input fields, and click on enter, the tag appears on the other input field.`
