### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop

### ISSUE THREAD

**Issue by beeant** [prakhar1989/react-tags#33]
I encountered this problem when I'm trying to add new fresh tags (for example the tags is not saved in database, they don't have tag id)

So I'm thinking if we can add:
```javascript
{tag.id || i}
```
in here
https://github.com/prakhar1989/react-tags/blob/master/lib/reactTags.js#L188

I can add `tag.id` to all the new fresh tags, but I have to clean it back when sending them to the server. Because if I don't it will have conflict with the existing tags with same id.

Thank You

**Comment by prakhar1989** [comment]
Makes sense. Would you be interested in sending a pull request with this change in place? I'll be happy to merge that in!

**Comment by prakhar1989** [comment]
Oh and Happy New Year! :fireworks:

**Comment by beeant** [comment]
thank you for the merge! :)

**Comment by cklab** [comment]
Running into the same warning every now and again. Scenario is:

Enter tag with `{ name: "tag", id: 1 }` and then a new, non-existent tag `{ name: "New Tag" }`

"New Tag" will get the same "key" field.

Generating ID should be consistent and deterministic, IMO ignore user input when generating a key. Submitted PR #54

**Comment by francisrod01** [comment]
The same error.but my default tags are `['tag 01', 'tag 02', 'tag 03']` without a key.
