### ISSUE TITLE
send tags to the server while handleAddition is called

### ISSUE THREAD

**Issue by ashfaqrafi** [prakhar1989/react-tags#332]
I want to send tags each time I call handleAddition method, that is while I put enter in my keyboard a new tag will be created using handleAddition method and at the same time the tag will be sent to server through HTTP request. is it possible to achieve? if so what will be the code. I want to do same while I delete a tag. @prakhar1989 @mrdannael please help me out.

**Comment by ad1992** [comment]
@ashfaqrafi did you try making the api call in `handleAddition` prop itself ?
