### ISSUE TITLE
seems placeholder prop doesn't work

### ISSUE THREAD

**Issue by xubinzheng** [prakhar1989/react-tags#338]
I added placeholder prop into the component, seems not working?

------> code
![image](https://user-images.githubusercontent.com/9353989/40924403-2dc73dc8-67e5-11e8-8548-3b17f329928b.png)

-------> also tried
![image](https://user-images.githubusercontent.com/9353989/40924808-2ba6f578-67e6-11e8-9b1d-4de27a39a2ee.png)

-------> result
![image](https://user-images.githubusercontent.com/9353989/40924429-3c8616d6-67e5-11e8-8b48-e017b51ac41a.png)

**Comment by ad1992** [comment]
@xubinzheng it works here https://stackblitz.com/edit/react-tag-input-1nelrc . can you reproduce in stackblitz and share the link so I can look in to it.

**Comment by xubinzheng** [comment]
Thank you for your quick response. I tried the link you provided and it all worked fine.
will double check my dev environment.

Thanks
