### ISSUE TITLE
autocomplete is bugged?

### ISSUE THREAD

**Issue by yangtheng** [prakhar1989/react-tags#342]
Hi, I was trying to use autocomplete in my application and it didn't work, it produced an error in the console instead. I couldn't find an issue with my code so I decided to try implementing autocomplete in your example code. The same error occured:

Uncaught TypeError: query.toLowerCase is not a function
    at ReactTags.js:116
    ...

Please have a look as I would like to have the autocomplete for my application. Thanks and cheers!

**Comment by ad1992** [comment]
@yangtheng which react tags version are you using ? are you able to reproduce here https://stackblitz.com/edit/react-tag-input-1nelrc ?

**Comment by yangtheng** [comment]
Yes the same error can be reproduced in that example if I add an
autocomplete prop to ReactTags like this:

<ReactTags
tags={tags}
autocomplete
suggestions={suggestions}
delimiters={delimiters}
handleDelete={this.handleDelete}
handleAddition={this.handleAddition}
handleDrag={this.handleDrag}
handleTagClick={this.handleTagClick}
/>

Am I doing it right?

**Comment by ad1992** [comment]
@yangtheng yes its a bug. Would you like to give a PR for the fix ? If you revert to v4.9.1 it should work.
