### ISSUE TITLE
Custom Component For Tag Item

### ISSUE THREAD

**Issue by morozp** [prakhar1989/react-tags#351]
Hi. Thanks for ypur great job.

1) How I can add specific style for any tag?
for exmaple each tag has some tagStatus but if tagStatus === 'active' backgroudcolor should be green.
2) How to add title for tag's item if it has long string?

**Comment by ad1992** [comment]
@morozp 
1. This should be achievable with https://github.com/prakhar1989/react-tags#styling. Can you try this ?
2. I didn't get you here. What do you mean by adding title to tag ?

**Comment by morozp** [comment]
@ad1992 
1) I need different styles for any tags. Any of them should have tag Status == active (green color) but other should be red.
2) i meen  attribute title  <span title={'Tag text is long long long long long long long long long long long long long long long long long long long long long'}>Tag text  is long ...</span>

**Comment by ad1992** [comment]
@morozp currently we are not passing any other props to Tag component apart from what is supported so if we start passing the props example `status` in this case then you will control the styling. So we just need to pass the rest of the props. Would you like to give a PR for this ?

**Comment by atiqueansari1987** [comment]
I would like to pick it but can you tell me exactly what changes are needed here?

**Comment by ad1992** [comment]
@morozp @atiqueansari1987 we have added `className` prop which will help styling different tags.
