### ISSUE TITLE
Showing all items

### ISSUE THREAD

**Issue by slavikdenis** [prakhar1989/react-tags#36]
Could you please fix, if I set _minQueryLength_ to **1**, on click in the enter area, It would automatically show all the suggestions? Thanks

**Comment by alexdmiller** [comment]
If you set `minQueryLength` to 1, then 1 character is required to make the suggestions appear.

However, I think you should be able to set `minQueryLength` to 0 and have the suggestions appear when you focus the text input. This doesn't happen currently.

**Comment by y-takey** [comment]
+1   I want to show all the suggestions.

currently mininum value of `minQueryLength` is `1`. If setting `minQueryLength` to `0`, replace it with `2` inner the library.
https://github.com/prakhar1989/react-tags/blob/master/lib%2FSuggestions.js#L32

**Comment by y-takey** [comment]
It was resolved with the following work around. Maybe not a good way :(

```javascript
import _ from 'lodash';
import React, { Component } from 'react';
import ReactDOM from 'react-dom';
import { WithContext as ReactTags } from 'react-tag-input';

const suggestions = ["hoge", "fuga", "foo"];

export default class MyApp extends Component {
  constructor(props, context) {
    super(props, context)
    _.bindAll(this, "showAllSuggestions", "handleAddition")
  }

  showAllSuggestions() {
    // if using `WithOutContext as ReactTags`, use `this.refs.tag.setState`.
    this.refs.tag.refs.child.setState({ 
      selectionMode: true, 
      suggestions: suggestions, 
      query: "&nbsp;"
    })
  }
  componentDidMount() {
    let input = ReactDOM.findDOMNode(this.refs.tag).getElementsByTagName("input")[0];

    input.addEventListener('focus', this.showAllSuggestions);
    _.defer(() => { input.blur(); input.focus() });
  }
  handleAddition(tag) {
    // some process
    _.delay(this.showAllSuggestions, 300);
  }
  render() {
    return (
      <ReactTags ref="tag"
              suggestions={suggestions}
              handleAddition={this.handleAddition}
              autofocus={true}
              minQueryLength={1}
              autocomplete={1} />
    );
  }
}
```

**Comment by sinkcup** [comment]
Like this: https://select2.github.io/examples.html#tokenizer

suggest merge code of @y-takey

**Comment by sinkcup** [comment]
@y-takey `selectionMode: true` will forbidden add new tag.

It trouble me...

**Comment by saranshbansal** [comment]
@y-takey 
I've spent a day trying to implement your suggestion but it won't work. React API has changed a lot since your answer. Also, refs will vanish from the scene in further releases.

@prakhar1989 
Brother, can you remove the query check and just let me show all suggestions onClick (and make it configurable of course)? 
It will be a great help. Currently, I couldn't find any other plugin which could get me what I want.

**Comment by atoiv** [comment]
It's possible to override the problematic [`shouldRenderSuggestions`](https://github.com/prakhar1989/react-tags/blob/7049b832961bb178f08ba1cf5af25bef3c17ebd6/lib/Suggestions.js#L65) function by passing it as a prop of the same name to ReactTags component:

```js
const handleShouldRenderSuggestions = () => true;

function MyComponent(props) {
  const otherReactTagsProps = { /* ... */ }

  return (
    <ReactTags
      {...otherReactTagsProps}
      shouldRenderSuggestions={handleShouldRenderSuggestions}
    />
  );
}
```

This will make the list of suggestions to be always rendered.

Then just add css rules for hiding the suggestions list when the input is not focused:

```css
// with default classes
input.ReactTags__tagInputField:focus + .ReactTags__suggestions {
  display: block;
}

.ReactTags__suggestions {
  display: none;
}
```

**Comment by martyan** [comment]
I have created PR with desired functionality. Hope it gets reviewed and merged soon as there were no big changes in the code. Cheerz!

**Comment by cdreve** [comment]
I have also made a PR with that contains the changes from @martyan and also allow the possibility to use the keyboard to select a suggestion when `minQueryLength` is set to `0`. Also updated tests.

**Comment by mrdannael** [comment]
Merged :beers:
