### ISSUE TITLE
Is it possible to not trim the inputted text onChange?

### ISSUE THREAD

**Issue by con322** [prakhar1989/react-tags#361]
I am passing inputValue and an onChange function into react tags.

The problem is i am unable to add any spaces to the end of the inputted text i think this is because it is trimmed before it gets to the passed onChange method.

Not sure what the best option would be for this improvement/change. Either remove the trimming altogether and let users implement there own or pass trim as a prop which you can pass true or false.

**Comment by ad1992** [comment]
@con322 leading and trailing spaces will be trimmed, i didn't get your use case here. why do you need it not to be trimmed, can you explain?

**Comment by con322** [comment]
@ad1992 thanks for the quick reply. I am setting the input value therefore need to change the state using the onChange function, within the onChange function i set the state of inputValue which is passed to react-tag-input also within that function I have custom validation (validation doesnt do anything fancy other than display a message somewhere outside of the react-tag-input component), because the text is trimmed before it reaches my code it means that I cannot put spaces at the end of the thing i am typing i'd have to type the phrase and then go back and put the spaces in. Does that make sense?

**Comment by ad1992** [comment]
@con322 I am not sure If I got you right. I understood that spaces are trimmed before your callback is hit. But can you give an example of why the spaces are needed?

**Comment by con322** [comment]
@ad1992 because validation is done onChange therefore after every key press so if a users puts a space it's then trimmed before i can change the state.

**Comment by ad1992** [comment]
@con322 we trim the data only when the keys which are delimiters are pressed. So you can pass only enter key as a delimiter and use `handleAddition` callback. does that make sense ?

**Comment by richsell86** [comment]
@ad1992 I am also having the same issue and I believe it to be a bug.

**Comment by richsell86** [comment]
@ad1992 Any news on this?

**Comment by richsell86** [comment]
@add1992 I've recreated this issue. It's here https://stackblitz.com/edit/react-tag-input-953xaw 

It seems to me that this is a really simple fix, simply don't trim the text and send it as is. It's not like it's any of your code that is dependent on the text being trimmed, it's only consumers of the component who would subscribe to the event. Why not leave it up to them to trim the input if needed?

**Comment by ad1992** [comment]
@richsell86 @con322 got it. We shouldn't trim the for a controlled component. I will push the fix for this.

**Comment by ad1992** [comment]
this has been fixed @richsell86 @con322 . Thanks for reporting.
