### ISSUE TITLE
Getting error while rendering input tag

### ISSUE THREAD

**Issue by jaysb29** [prakhar1989/react-tags#382]
I am getting this error everytime I try to render the input
TypeError: Cannot read property 'tagInput' of undefined
ReactTags.render
webpack-internal:///./node_modules/react-tag-input/dist-modules/ReactTags.js:381:44
eval

**Comment by tricepa** [comment]
any luck with this?

**Comment by ad1992** [comment]
please share  [stackblitz link](https://stackblitz.com/edit/react-tag-input-1nelrc) for this issue so i can look in to it.
