### ISSUE TITLE
TypeError: this.state.classNames is undefined

### ISSUE THREAD

**Issue by ShrawanBK** [prakhar1989/react-tags#386]
I got this issue while trying to use react-tags.

**Comment by ad1992** [comment]
need more info on this. please share the [stackblitz link](https://stackblitz.com/edit/react-tag-input-1nelrc)

**Comment by ShrawanBK** [comment]
Hello,
I have a index.js file which is totally fine in its implementation. I
wanted to add something similar as mentioned in
https://stackblitz.com/edit/react-tag-input-1nelrc?file=index.js . I tried
to implement it, but do get an error saying this.state.classNames is not
defined. A small preview of the error is attached here with the mail !!
Thank you !!

**Comment by ad1992** [comment]
@ShrawanBK I can't find the preview as mentioned above. Can you share your index.js file ?

**Comment by fdutey** [comment]
Same same here. Looks like the UNSAFE_componentWillMount is not being ran

**Comment by soulclown** [comment]
@ShrawanBK @fdutey same problem here: as temporary solution i passed `classNames` as props.

`<ReactTags {...props} classNames={{tagInput:{}}} />`

Seems something is wrong on default prop for `classNames`. @ad1992 Let us know.

**Comment by soulclown** [comment]
@ShrawanBK  @fdutey Same here. I solved pinning the version:
`"react-tag-input": "5.0.1"`
The question is: why in the last version classNames in state is null?

**Comment by ad1992** [comment]
@ShrawanBK @fdutey @soulclown it works when I try with classNames.Would be great if someone can share the [stackblitz link](https://stackblitz.com/edit/react-tag-input-1nelrc) so I can look into it.

**Comment by ad1992** [comment]
@ShrawanBK @soulclown @fdutey  which react version are you using ? Please make sure you use `16.3` so that ` UNSAFE_componentWillMount` is triggered
