### ISSUE TITLE
Add autoCapitalize prop

### ISSUE THREAD

**Issue by daninfpj** [prakhar1989/react-tags#395]
Similar to autofocus, placeholder and maxLength that are passed to the input field, it would be nice to have an autoCapitalize prop (and maybe some other input props?).

**Comment by ad1992** [comment]
IMO auto capitalize is something which should be handled by the parent component itself and you can set the state after capitalizing and pass it to react tags.

**Comment by daninfpj** [comment]
I meant it more as a way to control the input methods on the field, specifically to disable autocapitalize on mobile devices’ software keyboards, more than to do some processing on the input which can be done later as you suggest.

In general I think you should be able to control all valid properties for the input field.

**Comment by ad1992** [comment]
I get your point but I am not very sure if we should add autocapitalize prop, @prakhar1989 what do you think ?
