### ISSUE TITLE
Check if addEventListener exists before using it for server side rendering

### ISSUE THREAD

**Issue by TomCaserta** [prakhar1989/react-tags#41]
To allow for server side rendering, we should remove any browser specific function calls or feature detect them before attempting to use them otherwise it will stop working on setups such as react-php-v8js.

**Comment by rnicholus** [comment]
I'm not seeing any explicit browser-specific calls in the code, and react-tags doesn't use `addEventListener`. I'm going to close this, but if I've missed something, please let me know.

**Comment by TomCaserta** [comment]
Oh thats odd, I may have placed this on the wrong repository! I'll have a look through now. Sorry.
