### ISSUE TITLE
Vulnerable React-dom v16.4.1

### ISSUE THREAD

**Issue by alexsheppard11** [prakhar1989/react-tags#415]
Greenkeeper has updated _react-dom_ to 16.4.1:
https://github.com/prakhar1989/react-tags/commit/96b8b3f698e2620b7607a6e45c91c432767e492d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

which has the following vulnerability:  https://reactjs.org/blog/2018/08/01/react-v-16-4-2.html

Updating to 16.4.2 is enough to resolve this security issue. There is PR #383 created by greenkeeper for this change too.

Can this be resolved please?

**Comment by ad1992** [comment]
@AlexanderTserkovniy this has been fixed. thank you for reporting this.
