### ISSUE TITLE
a11y: tab key is ignored when in text input field

### ISSUE THREAD

**Issue by rnicholus** [prakhar1989/react-tags#42]
In the `handleKeyDown` function in reactTags.js, [a delimiter key's default action is _always_ prevented](https://github.com/prakhar1989/react-tags/blob/v2.2.0/lib/reactTags.js#L108). The comment in the code mentions that this is in place to prevent delimiters from becoming part of the tag, which makes perfect sense. However, with the tab key as a delimiter, this prevents keyboard access to the document if the tag input field is focused. This is a significant accessibility issue. To fix this, I think tab characters need to be treated as special. In other words, in `handleKeyDown`, if the tab key has be pressed and it is a delimiter, only prevent the default action if the field is _not_ empty (which seems to correspond to `state.query`). With an empty text input, the user can tab and shift-tab to navigate the document, as expected. With a non-empty text input, a tag will be created on tab/shift-tab, and then the next tab/shift-tab will allow the user to navigate the document again.

I'm happy to open up a PR, but wanted to get your thoughts on this solution first.

**Comment by rnicholus** [comment]
@prakhar1989 Seems you may be quite busy with your many other projects/repos. If that is true, I'd be happy to help out with this library, as time allows, as a contributor.

**Comment by prakhar1989** [comment]
Hi Ray! Sorry again for the late response.  

> I'd be happy to help out with this library, as time allows, as a contributor.

This sounds great. I'd surely welcome any help in making this library better. Should I add you as a collaborator so that you get more control over the direction of the project? Let me know what you have in mind!

**Comment by rnicholus** [comment]
Adding me as a collaborator sounds acceptable to me. If you are comfortable with me pushing out new versions as well, you'll want to consider adding me to the project in npm as well. That is explained at https://docs.npmjs.com/cli/owner.

**Comment by prakhar1989** [comment]
Added you as a collaborator, Ray! I'm fine with adding you on NPM too but I feel that initially both of us discuss whenever we're pushing out a new release. If I see myself being a bottleneck, I'll surely add you on NPM. Does that sound acceptable?

**Comment by rnicholus** [comment]
Yep, sounds great to me! I have at least one update to make (this case) and I'll try to assist with other cases as time allows. Also note that we (at Widen) _have_ created a story for an upcoming sprint to look into adding unit tests for this project. More info on that in the unit testing issue later.

**Comment by prakhar1989** [comment]
Wonderful! Thank you for stepping up for contributing to this library! :grin

**Comment by rnicholus** [comment]
I see this as being part of 2.2.1, as this is a bug, IMHO.

**Comment by prakhar1989** [comment]
:+1:

**Comment by rnicholus** [comment]
@prakhar1989 Changes for this fix are being staged on hotfix/42-a11y. If you have no objections, I'll merge into master and then perhaps you can push 2.2.1 to npm.

**Comment by prakhar1989** [comment]
Of course @rnicholus. Go ahead :+1:

**Comment by rnicholus** [comment]
This is now on master. `npm publish` at your convenience @prakhar1989!

**Comment by prakhar1989** [comment]
Just published it on NPM, Ray! Thanks a ton =)
