### ISSUE TITLE
Tag validation - input cleared if invalid.

### ISSUE THREAD

**Issue by tjohnsonSpireDigital** [prakhar1989/react-tags#428]
I added a simple email validation inside  handleAddition to prevent the tag being added to state and set the input's background color to red.  The only issue is the input is still cleared because _this.resetAndFocusInput() still gets called.  Is there a way to avoid this?

Thanks!

**Comment by ad1992** [comment]
@tjohnsonSpireDigital can you share your code ?

**Comment by tjohnsonSpireDigital** [comment]
Here is a quick and dirty implementation.  You will see that on adding an invalid email the input is cleared.  Thank you! 

https://stackblitz.com/edit/react-tag-input-ymbi1j?file=ReactTag.js

**Comment by prjctnxt** [comment]
I have this problem too when trying to validate tags that start with or contain blacklisted characters.

Ideally returning false from .handleAddition() would prevent the input from being cleared, or better yet a dedicated .validateAddition() that returns a boolean.

**Comment by kgodey** [comment]
I would also like a way to validate additions so that the input doesn't get cleared automatically.
