### ISSUE TITLE
delimeters not support for some browsers

### ISSUE THREAD

**Issue by YasiruDev** [prakhar1989/react-tags#432]
const delimiters = [KeyCodes.comma];  // [188]
i have tested my app with some browsers (mobile browser,desktop browser).but it's not working with some browsers.
all tested browsers are updated and it's chrome browser

**Comment by ad1992** [comment]
can you specify which browser you mean its not working @YasiruDev ?

**Comment by YasiruDev** [comment]
some mobile browsers. Actually it's happen in Android web browsers.working fine in desktop browsers
