### ISSUE TITLE
Invalid scss import

### ISSUE THREAD

**Issue by znarf** [prakhar1989/react-tags#434]
In the https://github.com/prakhar1989/react-tags/commit/063132cc09af9eff748b4e0eea12faf0188ea75b commit, there is now `import '../styles/react-tags.scss';`.

This is translated in the built version as `require('../styles/react-tags.scss');` which is invalid by default.

To work properly, looks like this is requiring a specific environment, such as a dedicated webpack loader. I would advise to remove that requirement. 

This is a breaking change for us at Open Collective: https://github.com/opencollective/opencollective-frontend/pull/1003

**Comment by foladipo** [comment]
I am experiencing the same problem too. Attempts to import ReactTags fail with the error: 
```
(function (exports, require, module, __filename, __dirname) { .react-tags-wrapper{
                                                              ^

SyntaxError: Unexpected token .
```

I'll probably install an older version pending when this issue is resolved.

**Comment by pilarArr** [comment]
> ```
> (function (exports, require, module, __filename, __dirname) { .react-tags-wrapper{
>                                                               ^
> 
> SyntaxError: Unexpected token .
> ```


I also have this problem

**Comment by Iuriy-Budnikov** [comment]
Any updates?

**Comment by Ravim-addweb** [comment]
Any updates yet guys?

**Comment by ad1992** [comment]
Sorry I was a little busy. I am working on this and the fix for this will be live soon.
