### ISSUE TITLE
Add color to tags

### ISSUE THREAD

**Issue by tbarlow12** [prakhar1989/react-tags#437]
For a project we're working on, there is a color associated with each tag. Is there currently an option for setting color? Any potential workarounds?

**Comment by ad1992** [comment]
@tbarlow12 you can pass text of the tags as html element. Does that help ?

**Comment by tbarlow12** [comment]
@ad1992 what would that look like on adding tags? for example, if I have:

**Comment by tbarlow12** [comment]
Sorry, I realize that's a loaded question without much context. We're just wrapping this in our own component with a lot of sample code provided:

**Comment by ad1992** [comment]
@tbarlow12 what i meant is you can pass text of the tag as an html element example `<span className ="custom-color">Hello</span>` something like this which you style as per your need and it.

**Comment by tbarlow12** [comment]
@ad1992 that makes sense. Thank you!

**Comment by ad1992** [comment]
awesome 👍

**Comment by mgoldenbe** [comment]
@tbarlow12 This affects only the style of the text. Is it possible to customize the background color of the tag?
