### ISSUE TITLE
Read only view

### ISSUE THREAD

**Issue by aaronucsd** [prakhar1989/react-tags#46]
Is there a way to show the tags without the edit mode? Like i do not want to show a delete x or input field to add more tags. Just want to list my tags.

**Comment by vkbansal** [comment]
You can try passing `null` to `removeComponent` prop if you do not want to show delete`x`.

**Comment by aaronucsd** [comment]
I tried but didn't work. Maybe i did it wrong?

`        <ReactTags tags={tags}
          suggestions={suggestions}
          removeComponent={null}
          handleDelete={this.handleDelete}
          handleAddition={this.handleAddition}
          handleDrag={this.handleDrag} />`

**Comment by vkbansal** [comment]
try using empty `<span/>` tag like this
```
<ReactTags tags={tags} suggestions={suggestions} removeComponent={<span/>} handleDelete={this.handleDelete} handleAddition={this.handleAddition} handleDrag={this.handleDrag} />
```

**Comment by aaronucsd** [comment]
That gave me errors.

`Warning: Failed propType: Invalid prop `removeComponent` of type `object` supplied to `ReactTags`, expected `function`. Check the render method of `DragDropContext(ReactTags)`.`

**Comment by vkbansal** [comment]
`removeComponent` must be a function, according to the `src`;

So use `() => <span/>` instead

**Comment by aaronucsd** [comment]
this works but i still need a view only mode, meaning the input field needs to go away (i prefer not have to add css to do this).

`removeComponent = () => <span/>;
        <ReactTags tags={tags}
          suggestions={suggestions}
          removeComponent={this.removeComponent}
          handleDelete={this.handleDelete}
          handleAddition={this.handleAddition}
          handleDrag={this.handleDrag} />
`

**Comment by vkbansal** [comment]
OK I'll try putting up a PR for it.

**Comment by aaronucsd** [comment]
Thanks! It be great just to have a easy flag to set to make it all read only (no delete x and input), as this is a real use case, where i show tags that does not allow for edit.

**Comment by vkbansal** [comment]
Added in #49

**Comment by aaronucsd** [comment]
Hi . Thanks for putting this in. I saw it and did a `npm update` but did not get the latest. Is it because we didn't update the version?   "version": "2.2.2",

**Comment by aaronucsd** [comment]
I did a npm update, and i think i got the latest, as i was able to add the new prop but did not see the readonly mode kick in.

from the call:
// INIT FAKE DATA
const fakeData = {
  tags: [{ id: 1, text: 'Apples' }],
  suggestions: ['Banana', 'Mango', 'Pear', 'Apricot', 'Peach', 'Strawberry'],
};

const options = {
  readOnly: true,
};

const elementTable = <TagList data={fakeData} options={options} />;
render(elementTable, compNode);
---------------------------------------
`inside of my component wrapper of ReactTags
        <ReactTags tags={tags}
          suggestions={suggestions}
          handleDelete={this.handleDelete}
          handleAddition={this.handleAddition}
          handleDrag={this.handleDrag}
          readOnly={this.props.options.readOnly}/>`

>

**Comment by aaronucsd** [comment]
maybe bump the version and re-publish?

**Comment by vkbansal** [comment]
If you require it urgently, you can change your package.json as follows
```
"react-tag-input": "prakhar1989/react-tags"
```

and run npm update

**Comment by aaronucsd** [comment]
Interesting. When can i get it through a regular update? I thought the PR
was approved and merged, no?

On Mon, Feb 29, 2016 at 4:57 PM, Vivek Kumar Bansal <
notifications@github.com> wrote:

> If you require it urgently, you can change your package.json as follows
>
> "react-tag-input": "prakhar1989/react-tags"
>
> and run npm update
>





Regards,
-Long Huynh

**Comment by vkbansal** [comment]
depends on @prakhar1989

**Comment by aaronucsd** [comment]
I see. :)
I thought it was approved, as you updated the readme.



Regards,
-Long Huynh

**Comment by vkbansal** [comment]
@prakhar1989 Just did it

**Comment by aaronucsd** [comment]
Yeah I saw. Lol. Thanks man. This is great.

**Comment by aaronucsd** [comment]
Got it now! Works like a charm. Only thing i would comment on is when it's
readOnly mode, the drag-n-drop is disabled but i still get a cross mouse
icon on hovering. We might want to take that out too so it's not confusing.
Else perfect. Thanks!



Regards,
-Long Huynh

**Comment by cklab** [comment]
Running into an issue with the readOnly feature: page breaks unless we explicitly set autofocus to false.

**Comment by tommoor** [comment]
looks like this feature is now in the library and this should be closed?

**Comment by prakhar1989** [comment]
Thanks for pointing this out @tommoor.
