### ISSUE TITLE
Pass event on handleDelete and on handleAdd

### ISSUE THREAD

**Issue by melenaos** [prakhar1989/react-tags#469]
I want to use a common function for handleDelete and handleAdd and the way I am doing now for other inputs is by using a data-name to get the state member i need to update.

<input data-name="example1" value={this.state.example1} onChange="onChange" />

That way I can get the data-name using the event from the onChange function

onchange(event){const name= event.target.getAttribute('data-name')....}

ReactTags is passing i on handleAdd and tag on handleDelete.

It would be beneficial to pass event next to these two parameters so we can get a handle to the element triggering this event.

As I see in the source code the event seems to pass allong but when I try to get it while using the function `handleAdd(tag, event)` I get undefined for event.

**Comment by ad1992** [comment]
@melenaos event is being not passed in  prop`handleAddition`.  
would you like to give pr ?

**Comment by melenaos** [comment]
Pr for pull request? I haven't made one yet but it's an easy task to start with.

So I will pass as second parameter the click event?

This will bring the needed information to the consumer of the component.

I will work on that tomorrow.

?p??t?ste t? Outlook ??a Android<https://aka.ms/ghei36>

________________________________

**Comment by ad1992** [comment]
@melenaos yes this will be quick fix. you can just pass the `event` to handleAddition and it should be done.

**Comment by melenaos** [comment]
I did the pr but that didn’t solve my problem.

 

My problem was that I wanted a way to distinguish an instance of ReactTag from another instance so I can use common handleAddition and handleDelete functions.

 

When I have two react tags I need to create two couples of functions, one for each tag. 

 

My point with the event was that I could read a data-attribute from the `<ReactTag />` and that way I could distinguish when my common function got triggered.

 

Instead of getting an event from the ReactTag I get an event from the <input /> that it’s contained within the react tag but with no way to access the data-attribute that could help me to distinguish it from the other `<ReactTag />`.

 

Do you have any suggestion of how to use multiple `<ReactTag />` within the same page with common event functions?

**Comment by ad1992** [comment]
@melenaos why not bind the common function and pass a third param which tells you from which component it was triggered
