### ISSUE TITLE
permit minimum query length of 0

### ISSUE THREAD

**Issue by shedali** [prakhar1989/react-tags#47]
By default, if no minQueryLengthis set, it defaults to 2. Suggestions begin to show after two characters are typed.

I would like to set this to 0 so that suggestions display immediately; however, by doing so the following code evaluates to false so it defaults to 2.

https://github.com/prakhar1989/react-tags/blob/master/lib/Suggestions.js#L32

**Comment by jacobcarpenter** [comment]
As a workaround, it looks like `-1` is valid input and would result in the desired behavior.

**Comment by prakhar1989** [comment]
Although, @jacobcarpenter's method is a hack, I support this! Thanks @jacobcarpenter's for sharing 👍
