### ISSUE TITLE
Element type is invalid: expected a string...

### ISSUE THREAD

**Issue by dark-swordsman** [prakhar1989/react-tags#472]
Hi there,

I am getting, "Uncaught (in promise) Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object." when I try to use the ReactTags element.

We are currently running React v14 on our project and haven't had the chance to upgrade to v16. It seems to be some sort of issue with it not being at least React v16.3.0 from my research. I tried installing react-dnd separately with no luck. Upgrading to React v16 is on our list, but this feature is priority over that at the moment.

I did notice, though, that in the TS files of the module, the `WithContext` class is completely empty. I haven't worked with TS and I have no knowledge of how to make node_modules like this, but is this correct?

This error seems to usually point to how the components are imported/exported.

**Comment by ad1992** [comment]
@dark-swordsman minimum version needed for the latest release in 16.3 since features like staticDerivedStateFromProps wont be available otherwise. in case you are using react 14 then you will have to use older version of this library
