### ISSUE TITLE
Example broken

### ISSUE THREAD

**Issue by Falieson** [prakhar1989/react-tags#476]
Hello! i use this example when i'm giving technical interviews (the interview is to replicate the tagger component) but it appears that over the weekend an update broke the example!

![image](https://user-images.githubusercontent.com/1538572/51865553-76655980-22fb-11e9-9edd-588a2faf9b45.png)

**Comment by ad1992** [comment]
@Falieson `react, react-dnd,react-dnd-html5-backend,react-dom` should be installed as peer dependencies. please make sure you install it.

**Comment by Falieson** [comment]
@ad1992  Sorry I wasn't clear enough, when you go to http://prakhar1989.github.io/react-tags/example/ its broken

**Comment by ad1992** [comment]
@Falieson pls refer to https://stackblitz.com/edit/react-tag-input-1nelrc for the example. Will be updating the link in the description as well

**Comment by Falieson** [comment]
Sweet - thanks
