### ISSUE TITLE
Adding Sections to suggestions

### ISSUE THREAD

**Issue by andresmechali** [prakhar1989/react-tags#479]
Hi! For my current project I need to display the suggestions split into different sections, with their corresponding title. I would gladly start working on it and send a PR, if you agree.

**Comment by ad1992** [comment]
@andresmechali i didn't get you. can you explain it a bit more ?

**Comment by andresmechali** [comment]
Yes sure! When I type and get suggestions, I would like to have them divided according to what type of suggestions they are. So, for example, if I search for 'ap', I would like to have a section title called 'Fruits' under which I can see 'APple', 'APricot', etc., and then another Section might be titled 'Countries' and would have 'jAPan' and 'singAPore' .

**Comment by ad1992** [comment]
@andresmechali we have added `renderSuggestion` prop where you can render your own custom suggestions. can you check if you can use this prop to render with sections https://github.com/prakhar1989/react-tags#renderSuggestion
