### ISSUE TITLE
Not working WithOutContext as ReactTags.

### ISSUE THREAD

**Issue by neerajdwiv** [prakhar1989/react-tags#480]
package.json
		"react": "^16.4.0",
		"react-dnd": "^7.0.2",
		"react-dnd-html5-backend": "^7.0.2",
		"react-tag-input": "^6.1.0",

import { WithContext as ReactTags } from 'react-tag-input'

ReactTags is working as intended when using WithContext.

import { WithOutContext as ReactTags } from 'react-tag-input'

ReactTags when using WithOutContext is not showing tags but input for tag only. 
< DragDropContextProvider backend={HTML5Backend}>
...
< /DragDropContextProvider>

**Comment by mateoSerna** [comment]
I also have this problem. Same dependencies but with "react": "^16.6.3"

**Comment by x5engine** [comment]
this is shit! wtf did happen to this package???

**Comment by ad1992** [comment]
@neerajdwiv can you share the stackblitz link with your code so I can look into it.

**Comment by x5engine** [comment]
what's the ETA of this issue??

**Comment by mateoSerna** [comment]
@neerajdwiv Have you resolved the issue? I just reinstall the dependencies and everything worked as expected.

**Comment by x5engine** [comment]
@mateoSerna I moved to react tags autocomplete and it works fine

**Comment by MarcoAntonioAntunes** [comment]
Having the same issue. WithOutContext isn't working as expected.

**Comment by ad1992** [comment]
react, react-dnd, react-dom and react-dnd-html5-backend have been moved to peer dependencies so please make sure you install the peer dependencies correctly.
It works as expected https://stackblitz.com/edit/react-tag-input-pg2ztz?file=App.js

**Comment by ad1992** [comment]
@x5engine @neerajdwiv @mateoSerna @MarcoAntonioAntunes  there is no issue with the package. 
You can check the link https://stackblitz.com/edit/react-tag-input-pg2ztz?file=App.js 
please make sure you install the peer dependencies correctly.

**Comment by mateoSerna** [comment]
@ad1992 you're right. It's working now, Thank you!

**Comment by ad1992** [comment]
closing this since all works fine 👍
