### ISSUE TITLE
[Issue] Filtering and updating suggestions

### ISSUE THREAD

**Issue by dmossie** [prakhar1989/react-tags#484]
I want to show all suggestions when I click the input field. So I set minQueryLength to 0.

However I want to only show the suggestions that are not included in my current tags. I changed my suggestions prop, but that didn't update react-tags.

I noticed I could use handleFilterSuggestions for this, however it is not called when the input field is first clicked, and is only called on keystroke.

However since I want to only show the suggestions which are not tags with a minQueryLength of zero, this is an issue.

Can someone please help me out? I need to either be able to filter onClick of the suggestion box, or update the suggestions itself

**Comment by dmossie** [comment]
Haven't tested it, but I'm thinking L197 of ReactTags needs something like this:

const suggestions = this.state.suggestions;
if (this.props.suggestions && this.props.minQueryLength && this.props.minQueryLength === 0){
	suggestions = this.filteredSuggestions(query, this.props.suggestions);
}
this.setState({ 
	isFocused: true,
	suggestions: suggestions
});

**Comment by ad1992** [comment]
@dmossie seems like the issue is similar to https://github.com/prakhar1989/react-tags/issues/488 ?

**Comment by dmossie** [comment]
@ad1992 Yeah it looks like the issues we are having are coming from the same problem with the library.
