### ISSUE TITLE
`autocomplete` and `addTag` logic broken by default

### ISSUE THREAD

**Issue by ZebGirouard** [prakhar1989/react-tags#486]
At the moment, `ReactTags.js`, on line 466 has this conditional:

```
    if (_this5.props.autocomplete) {
      var possibleMatches = _this5.filteredSuggestions(tag[labelField], _this5.props.suggestions);

      if (_this5.props.autocomplete === 1 && possibleMatches.length === 1 || _this5.props.autocomplete === true && possibleMatches.length) {
        tag = possibleMatches[0];
      }
    }
```

If you look closely, you'll notice a typo...at least I think it's a typo, because it causes tag suggestion selection to ALWAYS select the first element in a list of suggestions.

`&& possibleMatches.length` <== that should (I'm like 99% sure) say `&& possibleMatches.length === 1`

My workaround for now is to set the prop `autocomplete={ 1 }`, because `autocomplete` causes the first item in a list to be selected, whether I click on the second, third, fourth, etc item.

Do y'all want me to file a PR for this?  It's 6 characters including spaces, and would probably help a lot of people.

**Comment by ZebGirouard** [comment]
Hope that PR is all you need...full project search did not show me `possibleMatches.length` anywhere else, but with no feedback, I had to guess that "my fix" is "the fix".

**Comment by ad1992** [comment]
@ZebGirouard sorry for the late reply and thanks for the PR. I agree with you that first element should only be selected when only one match is found but I could not understand 
`autocomplete causes the first item in a list to be selected, whether I click on the second, third, fourth, etc item.`
Do you mean when you pass `autocomplete` as true and while typing if there are multiple matches and you select some `x` element but in UI it shows up first element ?

**Comment by ZebGirouard** [comment]
What a bummer.  I really hope this issue was fixed somewhere else.  To be completely frank, I am a little disappointed that this issue remains unfixed because I was unsure how to add a test case to a project I've never touched before.  I think it cannot be stressed enough how many people fall off open source projects before they get a chance to really help. Not sure why someone else couldn't have pushed up a `spec` change on my branch, or given me some advice on how to complete it, in the two months this issue and PR have been open.
