### ISSUE TITLE
[Issue] Suggestion refresh after handleAddition execution

### ISSUE THREAD

**Issue by LukaszNowakPL** [prakhar1989/react-tags#488]
**Issue**
Suggestions list does not refresh and contains suggestion already taken.

**Steps to reproduce**
- Make suggestion panel open (in my case after clicking on input form - minQueryLength={0}
- Choose one of suggestions provided
- Make suggestions panel open again

**My code**
```
<ReactTags
	tags={tags}
	suggestions={suggestions}
	handleAddition={this.handleAddClick}
	handleDelete={i => this.handleDeleteClick(tags, i)}
	minQueryLength={0}
	autocomplete={true}
	autofocus={false}
	handleFilterSuggestions={this.handleSuggestions}
/>
```

**Explanation**
My `handleAddClick` method modifies `tags` and `suggestions` so first one contains taken element and second one does not (checked by console.log one line before render). Nevertheless component update seems not to picking up new `suggestions` list.

Sneaking to the code, it seems `state.suggestions` is modified only on constructor as well as during `handleChange` execution. This method is executed only by input's `onChange`. In this case `suggestions` list is refreshed only after typing at least one sign into input form.

**Comment by ad1992** [comment]
@LukaszNowakPL I agree with you we should refresh the suggestions. I think We should refresh only when `allowUnique` prop is false. What are your thoughts ?

**Comment by Gibr** [comment]
Maybe it would be better to filter out somehow selected tags from suggestion list during `filteredSuggestions` whithout modifyng suggestions list?
