### ISSUE TITLE
How can I check if someone clicked between the tags?

### ISSUE THREAD

**Issue by Akitsu** [prakhar1989/react-tags#490]
Is there a way to check if you clicked between the tags? I want to move the input field between the tags based on the where you have clicked.

I’m trying to create simple and easy calculations in my application. The goal is to have ‘zero-fault’ calculations with variables and operators.

An example would be: [Var1] [+] [Var2] [-] [Var3]

All variables and operators will become tags. Everything is working except the possibility to click ‘between’ tags and add new variables. I’ve tried the following options:
- Built in handleTagClick function
   - No detection when clicking between the tags
- onClickEvent on the wrapper
   - Can’t calculate when clicking between, because I need to know the width of the tags. 

So do you guys know any option to get this functionality. I’ve got it working to get between tags with the arrowkeys. Did it trough CSS and flexbox order.

**Comment by ad1992** [comment]
@Akitsu I didn't what you mean by `clicking between the tags` . 
Do you mean when you have `[Var1] [+] [Var2] [-] [Var3]` you click near [var3] and add a operator ?
Could you explain more if i got you wrong ?
