### ISSUE TITLE
Using two react-tags components on same page

### ISSUE THREAD

**Issue by gabrieldonadel** [prakhar1989/react-tags#494]
I'm using these react-tags as an input filter for a table, so I would need to use the same component many times on a single page, is that possible? I've tried creating a two dimension array as tag state but didn't work quite well.

**Comment by ad1992** [comment]
@gabrieldonadel i didn't get you. can you explain more ? or may share a code snippet ?

**Comment by Simoneth** [comment]
Hi,
I have the same problem...
I have an array of elements in the same page, each one should have different tags.

I tried this: 

`const [tags, setTags] = React.useState([{}]);`

to try map as below:

```
<ReactTags
    tags={tags[index]}
    ...
    autocomplete
/>
```

This fails as: "TypeError: tags.map is not a function"

So how can I achieve that? I need to store objects arrays of tags.

Thanks.
