### ISSUE TITLE
Insert Html <label> befront __tagInputField

### ISSUE THREAD

**Issue by daothithientamm** [prakhar1989/react-tags#502]
i want to insert Html <label>Create new tag: </label>  between ReactTags__tagInputField and ReactTags__tag . Can you help me custom this with some example. Thks so much
label:"help wanted"

**Comment by ad1992** [comment]
@daothithientamm you can pass html in text attribute of the tag, does that help ?

**Comment by daothithientamm** [comment]
Thanks for your response. Could you give me a example for that ?  Please.
I have attached the file described in this mail.
I have learned about React for a month,  I look forward to receiving your
help. Thank you so much.


Vào Th 4, 27 thg 2, 2019 vào lúc 01:41 Aakansha Doshi <
notifications@github.com> đã viết:

**Comment by daothithientamm** [comment]
`` <ReactTags
                            allowDragDrop={false}
                            inline={false}
                            tags={tags}
                            suggestions={suggestions}
                            delimiters={delimiters}
                            handleDelete={this.handleDelete}
                            handleAddition={this.handleAddition}
                            handleDrag={this.handleDrag}
                            handleTagClick={this.handleTagClick}
                        />

**Comment by ad1992** [comment]
@daothithientamm couldn't find the file which you referred above. You can just pass html in text attribute example `{id: 1, 'text': '<span>hello</span>'}`

**Comment by daothithientamm** [comment]
<ReactTags
                            allowDragDrop={false}
                            inline={false}
                            tags={tags}
                            suggestions={suggestions}
                            delimiters={delimiters}
                            handleDelete={this.handleDelete}
                            handleAddition={this.handleAddition}
                            handleDrag={this.handleDrag}
                            handleTagClick={this.handleTagClick}
                        />
