### ISSUE TITLE
Comma delimiter key not working as expected on the chrome browser

### ISSUE THREAD

**Issue by i-shubhamprakash** [prakhar1989/react-tags#520]
**Expected behavior:**
The user should be able to enter tags when the comma delimiter key is pressed in chrome browser.

**Current Behavior:**
1) We can enter tags with ENTER key as the delimiter but not with COMMA key on chrome browser. The comma key instead of working as delimiter is getting input as a string in the tag.
2) It is working as expected on firefox browser. The problem seems to occur only with chrome browser

**Possible cause**
I inspected what is happening when I enter a delimiter key and found that  `handleAddition()` function is not getting invoked when comma key is pressed on chrome browser.

Note: To verify the issue, I also checked the documentation sample code link given on [(stackblitz.)](https://stackblitz.com/edit/react-tag-input-1nelrc). I opened the output live in a new tab on both chrome and firefox and got the same error!

**Device Used**
PC: DELL inspiron
OS: Linux Mint 19.1
Chrome browser version: Version 73.0.3683.86 (Official Build) (64-bit)

Thankyou.

**Comment by Gibr** [comment]
I tried to reproduce this bug, but i could not.
On chrome and firefox, ENTER and COMMA keys are working equally ([https://stackblitz.com/edit/react-tag-input-1nelrc](url)).
Are you sure about key kode produced by your comma key? Is it 188? You can check it here : [https://keycode.info/](url)

**Comment by i-shubhamprakash** [comment]
Yes, It works inside the virtual browser using the link you gave but once you click on "Open in new windows Live" button on top right, the same problem occurs I chrome. Enter key is behaving fine but not the comma key. Please check and confirm. Thankyou
