### ISSUE TITLE
IE11 The above error occurred in the <ReactTags> component: in ReactTags (created by DragDropContext(ReactTags)) in DragDropContext(ReactTags)

### ISSUE THREAD

**Issue by PushpakGit** [prakhar1989/react-tags#522]
I am facing above issue on **IE11** it is working on chrome/firefox
Following is the issue

"react-tag-input": "^5.0.2"

<div>
                          <ReactTags tags={[]}
                              suggestions={suggestions}
                              handleDelete={this.handleDelete}
                              handleAddition={this.handleAddition}
                              handleDrag={this.handleDrag}
                              delimiters={delimiters} />
                      </div>

In Console
============
**The above error occurred in the <ReactTags> component: in ReactTags (created by DragDropContext(ReactTags)) in DragDropContext(ReactTags)**

**Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.
    in ReactTags (at new_user.js:579)**

**Comment by ad1992** [comment]
@PushpakGit does this happen in latest version as well ?
