### ISSUE TITLE
How I can check email is valid ?

### ISSUE THREAD

**Issue by quanttn-0861** [prakhar1989/react-tags#524]

**Comment by quanttn-0861** [comment]
Hi there, I don't know how to check email is valid when entering the tags? Could you help me? Thanks

**Comment by atiqueansari1987** [comment]
You can use your email validation logic in handleAddition function and if passes you can add it to tag list.

```
handleAddition(tag) {
    var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    if (re.test(tag.text)) {
      this.setState((state) => ({ tags: [...state.tags, tag] }));
    } else {
      // show validation message to user
      console.log('Invalid email', tag);
    }
  }
```

**Comment by quanttn-0861** [comment]
> You can use your email validation logic in handleAddition function and if passes you can add it to tag list.
> 
> ```
> handleAddition(tag) {
>     var re = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
>     if (re.test(tag.text)) {
>       this.setState((state) => ({ tags: [...state.tags, tag] }));
>     } else {
>       // show validation message to user
>       console.log('Invalid email', tag);
>     }
>   }
> ```

Wow, it's exactly what I was looking for. Thank you so much :D
