### ISSUE TITLE
Suggestion: allowUnique callback?

### ISSUE THREAD

**Issue by alexyapp** [prakhar1989/react-tags#527]
I was trying to look for a way for when the package encounters a duplicate tag when allowUnique is set to display a toast message notifying the user that the tag is already added but there seems to be none or I may have overlooked it. So perhaps this would be a good feature to add? If so please point me to where I can make a contribution as I would very much love to help out (I am pretty new to this).

**Comment by ad1992** [comment]
how about showing inline error message instead of toast ?
