### ISSUE TITLE
I give up ...

### ISSUE THREAD

**Issue by prashantjain68** [prakhar1989/react-tags#546]
I really liked this component and wanted to use it in my application. I installed all dependencies with recommended versions but keep getting errors. 

I finally gave up.

**Comment by ad1992** [comment]
@prashantjain68 what errors did you get ? can you share a stackblitz or code sandbox link ?

**Comment by prashantjain68** [comment]
This is the error I get. It is a ReactDND issue. Seems like the index.js file has been renamed to "ReactDnD.min.js" and there is no "esm" folder under "dist"

 Error: Module build failed: Error: ENOENT: no such file or directory, open '/Users/me/git/myproject/node_modules/react-dnd/dist/esm/index.js'

On a different note, DnD should be included only if drag and drop is really required. I dont need DnD functionality because for me order is not important. This makes the application slightly light weight.

**Comment by prashantjain68** [comment]
... and below entries from package.json:

    "react-dnd": "^5.0.0",
    "react-dnd-html5-backend": "^3.0.2",
    "react-tag-input": "^6.4.0",

**Comment by prashantjain68** [comment]
<img width="851" alt="Screen Shot 2019-07-20 at 2 55 45 PM" src="https://user-images.githubusercontent.com/2547563/61584559-9f261900-aafe-11e9-8c5b-ed1ae24934a5.png">

**Comment by wortkotze** [comment]
I encounter the same issues :

`node_modules/react-dnd/dist/esm/index.js:1
W20190721-21:32:06.126(-4)? (STDERR) (function (exports, require, module, __filename, __dirname) { export * from './common';
W20190721-21:32:06.126(-4)? (STDERR)                                                               ^^^^^^
W20190721-21:32:06.126(-4)? (STDERR) 
W20190721-21:32:06.126(-4)? (STDERR) SyntaxError: Unexpected token export
W20190721-21:32:06.127(-4)? (STDERR)     at createScript (vm.js:80:10)
W20190721-21:32:06.127(-4)? (STDERR)     at Object.runInThisContext (vm.js:139:10)
W20190721-21:32:06.127(-4)? (STDERR)     at Module._compile (module.js:617:28)
W20190721-21:32:06.128(-4)? (STDERR)     at Object.Module._extensions..js (module.js:664:10)
W20190721-21:32:06.128(-4)? (STDERR)     at Module.load (module.js:566:32)
W20190721-21:32:06.128(-4)? (STDERR)     at tryModuleLoad (module.js:506:12)
W20190721-21:32:06.128(-4)? (STDERR)     at Function.Module._load (module.js:498:3)
W20190721-21:32:06.129(-4)? (STDERR)     at Module.require (module.js:597:17)
W20190721-21:32:06.129(-4)? (STDERR)     at require (internal/module.js:11:18)
W20190721-21:32:06.129(-4)? (STDERR)     at Object.<anonymous> (/bootstrap4/node_modules/react-tag-input/dist-modules/components/ReactTags.js:14:17)
W20190721-21:32:06.150(-4)? (STDERR)     at Module._compile (module.js:653:30)
W20190721-21:32:06.151(-4)? (STDERR)     at Object.Module._extensions..js (module.js:664:10)
W20190721-21:32:06.151(-4)? (STDERR)     at Module.load (module.js:566:32)
W20190721-21:32:06.152(-4)? (STDERR)     at tryModuleLoad (module.js:506:12)
W20190721-21:32:06.152(-4)? (STDERR)     at Function.Module._load (module.js:498:3)
W20190721-21:32:06.153(-4)? (STDERR)     at Module.require (module.js:597:17)
W20190721-21:32:06.154(-4)? (STDERR)     at require (internal/module.js:11:18)
W20190721-21:32:06.154(-4)? (STDERR)     at npmRequire (/.meteor/local/build/programs/server/npm-require.js:133:10)
W20190721-21:32:06.154(-4)? (STDERR)     at Module.useNode (packages/modules-runtime.js:664:18)
W20190721-21:32:06.155(-4)? (STDERR)     at ReactTags.js (packages/modules.js:1077:8)
W20190721-21:32:06.156(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190721-21:32:06.156(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)`

any ideas ? could this be an export issue?
