### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by sapegin** [prakhar1989/react-tags#55]
Because [it’s important](http://keepachangelog.com/).

**Comment by rnicholus** [comment]
A pull request that includes a changelog.md with the changes from previous releases would be appreciated. At that point, it will be easy to keep it up-to-date going forward. Short of that, you can already compare tags using GitHub's "compare" feature: https://help.github.com/articles/comparing-commits-across-time/.

**Comment by sapegin** [comment]
I can read commit log myself but I’m asking for a change log.

> *What makes unicorns cry?*
> Dumping a diff of commit logs. Just don’t do that, you’re helping nobody.

**Comment by rnicholus** [comment]
Since none of the many contributors to this project owe you anything in particular, perhaps you could become a contributor as well and get this changelog started. After all, this is how open source works.

**Comment by sapegin** [comment]
I don’t use this library anymore. And writing a good change log is a task that only the author can do properly. Of course if he cares about his users. I know how open source works.
