### ISSUE TITLE
Ref

### ISSUE THREAD

**Issue by igordeoliveirasa** [prakhar1989/react-tags#558]
How could I access throw ref={} ?

**Comment by zilahir** [comment]
i would like to access the `ref` also. is there a way to do it?

**Comment by ad1992** [comment]
Whats your use case ? Adding ref on the container where you are rending won't help ?

**Comment by zilahir** [comment]
@ad1992 the usecase is the following: 

when selecting a tag, (by clicking on it) the input looses focus, and i would like to put it back, so the user does not need to click back into the input every time a tag had been added. 

not sure i can achieve the same by putting a ref into the container div, and doing `containerRef.current.focus()`
