### ISSUE TITLE
Uncaught Invariant Violation: Expected to find a valid target.

### ISSUE THREAD

**Issue by francisrod01** [prakhar1989/react-tags#559]
Uncaught Invariant Violation: Expected to find a valid target.

I'm facing this issue when I drag a tag.

![image](https://user-images.githubusercontent.com/4691768/66673624-554d5a80-ec37-11e9-8122-c5c6d32ab1f6.png)

Envs:

- react@16.10.2
- react-dom@16.10.2
- react-tag-input@6.4.1
- react-dnd@5.0.0
- react-dnd-html5-backend@3.0.2

A related tag here: [Uncaught Error: Invariant Violation: Expected to find a valid target](https://github.com/react-dnd/react-dnd/issues/236)

**Comment by jmfsilva** [comment]
DND and a little buggy.
It rarely works and most of the times i'v that error.
Envs:
 - "react": "^16.9.0"
- "react-dom": "^16.9.0"
- "react-dnd": "^5.0.0" (as recommended)
- "react-dnd-html5-backend": "^3.0.2", (as recommended)

**Comment by jameswyse** [comment]
I'm getting the same error. I think it's because the `key` prop isn't stable

Currently it's set to `key={`${tag.id}-${index}`}` in [ReactTags.js:389](https://github.com/prakhar1989/react-tags/blob/master/src/components/ReactTags.js#L389)
Changing it to `key={tag.id}` fixed the problem for me!

**Comment by tankorsmash** [comment]
I'm having the same issue with dragging a tag and throwing the invariant error about not being able to find a target. 

Same as above, except 

    "react": "^16.8.0"
    "@hot-loader/react-dom": "^16.8.0"


Some potential causes is inconsistent ids (maybe based on their position on the array) and keys. We'll see if I can make any progress on my own error.
