### ISSUE TITLE
Can't not run the example with the latest react

### ISSUE THREAD

**Issue by zhouhao27** [prakhar1989/react-tags#564]
Got the following error message when I run your example code in `readme.md`.

> ./node_modules/react-tag-input/dist-modules/components/ReactTags.js

> Module not found: Can't resolve 'react-dnd'

Here is my package.json:

```
  "dependencies": {
    "react": "^16.10.2",
    "react-dom": "^16.10.2",
    "react-scripts": "3.2.0",
    "react-tag-input": "^6.4.1"
  },

```

It seems the `react-dnd` is not installed. But why? It's inside the `package.json` of `react-tag-input`.

**Comment by omkar-joshi** [comment]
@zhouhao27 `react-dnd` is marked as a peer dependency of `react-tag-input`. So you would need to install it along with `react-dnd-html5-backend`. See - https://github.com/prakhar1989/react-tags#installation
