### ISSUE TITLE
Bug: auto generate tag

### ISSUE THREAD

**Issue by SeongwoonHong** [prakhar1989/react-tags#575]
steps to reproduce

1. go to demo site
2. type india (which already exists, thus i'm not allowed to have this again)
3. remove india that you just typed
4. hit enter
5. it randomly generates a tag

**Comment by ad1992** [comment]
@SeongwoonHong I tried following the steps in https://stackblitz.com/edit/react-tag-input-1nelrc  but it works fine and doesn't generate any random tag.  Can you check and confirm ?
