### ISSUE TITLE
Bug: className property per tag has no effect

### ISSUE THREAD

**Issue by cs-manughian** [prakhar1989/react-tags#576]
Hi, I would like to have a specific className per draggable tag object, so I was using the options like so: [{ id: 1, text: 'TagGoesHere', className: 'reserved' }], but it does not seem to have any effect.

The property on the ReactTags component applies the "tag" className to every tag, but I would like to apply a className on an individual tag based on a certain associated data point. Is this a bug? Is there another way around this? This would really save a lot of time and would be greatly appreciated!

Thank you!

**Comment by eddiekimosabe** [comment]
This still appears to be an issue for me also. 
I would like to adjust the color of the tags based on a condition `[{ id: 1, text: 'text', className: 'red' }]` but it doesn't appear to do anything and continue to maintain the .guest-list__tag styles.

**Comment by eddiekimosabe** [comment]
It looks like the version that I was using was outdated. v6.2.0 and up appears to handle what I need 👍
