### ISSUE TITLE
How to use this lib in React 15.6.1

### ISSUE THREAD

**Issue by nileshyadav326** [prakhar1989/react-tags#578]
Here is the my package.json file.

    **"react": "^15.6.1",**
    "react-css-modules": "^4.7.1",
    "react-day-picker": "^6.2.0",
    "react-dom": "^15.6.1",
    "react-dropzone": "^4.2.1",
    "react-ga": "^2.3.4",
    "react-google-maps": "^8.5.0",
    "react-helmet": "^5.2.0",
    "react-icons-kit": "^1.0.7",
    "react-id-swiper": "^1.6.1",
    "react-input-range": "^1.2.1",
    "react-linkedin-insight": "0.0.2",
    "react-load-script": "0.0.6",
    "react-loadable": "^5.5.0",
    "react-masonry-component": "^6.2.1",
    "react-perfect-scrollbar": "^1.2.2",
    "react-rating": "^0.9.0",
    "react-read-more": "^1.0.0",
    "react-redux": "^5.0.6",
    "react-redux-form": "^1.16.4",
    "react-redux-loading-bar": "^3.0.0",
    "react-router": "3.0.0",
    "react-router-redux": "4.0.7",
    "react-router-scroll": "^0.3.0",
    "react-s-alert": "^1.4.0",
    "react-scroll": "^1.7.9",
    "react-scrollbar": "^0.5.4",
    "react-slick": "^0.16.0",
    "react-social-login": "^3.2.0",
    "react-sortable-hoc": "^0.6.8",
    "react-string-replace": "^0.4.1",
    **"react-tag-input": "^6.4.2",**
    "react-tooltip": "^3.4.0",
    "react-waypoint": "^8.0.0",
    "redux": "^3.7.2",
    "redux-api-middleware": "^2.3.0",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.2.0",
    "sass-loader": "^6.0.6",
    "style-loader": "0.18.2",
    "sw-precache-webpack-plugin": "0.11.4",
    "whatwg-fetch": "2.0.3"

[package copy.txt](https://github.com/prakhar1989/react-tags/files/4015764/package.copy.txt)

**Comment by ad1992** [comment]
@nileshyadav326 the react version should be 16+ as mentioned https://github.com/prakhar1989/react-tags#installation
