### ISSUE TITLE
I want to remove drag-n-drop tags because it's conflict with another drag-n-drop in form

### ISSUE THREAD

**Issue by tssghost89** [prakhar1989/react-tags#582]
I use react-file-drop, file-pond, and react-tags in the same form.
file-drop and file-pond drag-n-drop can't work because of react-tags.
Please add option to remove drag-n-drop on tags. I don't need to drag-n-drop tags.
Thank you.

**Comment by alex-polunochev** [comment]
Does this help?
```
  allowDragDrop={false}
```

**Comment by tssghost89** [comment]
I try this allowDragDrop={false} but still not working.
I just downloaded and changed component code.
