### ISSUE TITLE
how to limit tags number

### ISSUE THREAD

**Issue by sinkcup** [prakhar1989/react-tags#59]
eg: user can select living city, if not exist, user can input. this input should limit 1 item.

Like this: http://selectize.github.io/selectize.js/#demo-max-items

**Comment by magano** [comment]
For what I've tried currently you can only disable the handleAddition behaviour with a limit flag you can set by yourself.
The input cannot be disable since currently you have no control over the input component.

**Comment by ypling** [comment]
Yes you need to implement your limitation logic in handleAddtion function.
If you want to disable input. Please try something like this

<ReactTagInput
    ref={node => this._input = node.refs.child.refs.input}
    ...
/>
...
this._input.disabled = true;

**Comment by magano** [comment]
Thanks for the tip, it helped me out too

**Comment by herkyl** [comment]
The method that @ypling suggested doesn't work anymore. This is how you can get it working:
```jsx
<ReactTagInput
  ref={ref => this._input = ref.child.textInput}
/>
```

**Comment by Razboi** [comment]
This worked for me. Allows the user to type in but prevents the addition and input clearing.
```jsx
<ReactTagInput delimiters={tags.length < limit ? [KeyCodes.enter] : []} />
```
