### ISSUE TITLE
Error _reactDnd.DragDropContext thrown after importing

### ISSUE THREAD

**Issue by Stancobridge** [prakhar1989/react-tags#591]
I have 
"devDependencies": {
        "@babel/preset-react": "^7.0.0",
        "axios": "^0.19",
        "cross-env": "^7.0.2",
        "laravel-mix": "^5.0.4",
        "lodash": "^4.17.13",
        "react": "^16.13.1",
        "react-dom": "^16.13.1",
        "resolve-url-loader": "^3.1.0"
    },
    "dependencies": {
        "@babel/preset-env": "^7.9.6",
        "react-dnd": "^10.0.2",
        "react-dnd-html5-backend": "^10.0.2",
        "react-router-dom": "^5.1.2",
        "react-router-guards": "^1.0.2",
        "react-select": "^3.1.0",
        "react-spinners": "^0.8.1",
        "react-tag-input": "^6.4.2"
    }
but import { WithContext as ReactTags } from 'react-tag-input'; 
gives error below
app.js:48562 Uncaught TypeError: (0 , _reactDnd.DragDropContext) is not a function
    at Object../node_modules/react-tag-input/dist-modules/components/ReactTags.js (app.js:48562)

**Comment by krodo93** [comment]
Same Problem

**Comment by kush1509** [comment]
Same issue!

**Comment by Yupeng-li** [comment]
This library requires: 
`react-dnd: ^5.0.0
react-dnd-html5-backend: ^3.0.2
`
You are using react-dnd: 10.0.2 so it's not compatible with react-tags. You can downgrade react-dnd to 5.0.0 and it will work.

**Comment by p8ul** [comment]
Same issue here! I want to use some cool features on updated react-dnd (context hooks) but I can't because this package throws errors when react-dnd is updated 😞

**Comment by mayognaise** [comment]
Same here 😢

**Comment by ZeroCoolHacker** [comment]
same here

**Comment by danielrd** [comment]
Same here, It's nice if dependencies packages are compatible with the latest versions.

**Comment by ad1992** [comment]
I am not sure when I will be able to pick this up.  Please feel free to open PR for the same.

**Comment by lenoirdevinci** [comment]
I had the same issue so I changed my package.json as :
```
"react": "^16.13.1",
"react-dnd": "^5.0.0",
"react-dnd-html5-backend": "^3.0.2",
"react-dom": "^16.13.1",
```
And that fixed the issue
