### ISSUE TITLE
Add react-dnd and react-dnd-html5-backend as normal dependencies

### ISSUE THREAD

**Issue by agusterodin** [prakhar1989/react-tags#594]
Is their a particular reason why react-dnd and react-dnd-html5-backend are listed as peer dependencies instead of just normal dependencies? I have yet to encounter this in other react libraries.

**Comment by ad1992** [comment]
@agusterodin the reason was so it doesn't get bundled with the build and if the upstream library wants the drag and drop functionality it can install the deps.

**Comment by dakkafex** [comment]
> if the upstream library wants the drag and drop functionality it can install the deps.

I dont understand, this lib doesnt work unless DND is specifically installed, its a hard dependency, even if you dont want to use dnd

**Comment by agusterodin** [comment]
Wouldn't it be standard practice to define the version you want to use as a normal dependency? Suppose DND had a breaking change, at that point your library breaks since you are at the mercy of what the user installed as their peer dependency instead of the version you as the library creator deem as verified working and tested.

**Comment by eastrd** [comment]
> Wouldn't it be standard practice to define the version you want to use as a normal dependency? Suppose DND had a breaking change, at that point your library breaks since you are at the mercy of what the user installed as their peer dependency instead of the version you as the library creator deem as verified working and tested.

Two years fast forward, and I am experiencing the exact problem you mentioned...
