### ISSUE TITLE
how to set suggestions ID

### ISSUE THREAD

**Issue by sinkcup** [prakhar1989/react-tags#60]
now suggestions have no ID, they are only string. but they are from database, have ID, and will save ID.

like this:

```
    getInitialState: function() {
        return {
            tags: [ {id: 25, text: "Apples"} ],
            suggestions: [ {id: 12, text: "Banana"}, {id: 36, text: "Mango"}, {id: 41, text: "Pear"} ],
        }
    },
```

**Comment by ypling** [comment]
I think you need to convert your suggestions from an array of objects to an array of strings before pass into react-tags.
Then in your handleAddition function go find id use the user selected text from original array of objects.

It's better to have your suggestions store as an Object. Text as key and id as value. This way will be easy to find suggestion id by suggestion text and remove duplication automatically.

**Comment by michaelzoidl** [comment]
Ok, but what should i do if two suggestions have the same content?

In my case you can choose names from people, so if - and this case is realistic - there are two people with the same name after the selection from the __react-tags__ i cannot identify which one was selected? (_fyi at the moment we've just forenames_)

**Comment by michaelzoidl** [comment]
Okay, i've now some kind of work-around, i think for the end-users this is okay (or maybe some benefit!?)

```javascript
  render() {
   const persons = [{
     id: 'jf10f-120kf-2j9da-f39k',
     name: 'Georg'
   }, {
     id: 'vm91-f912j-3fk12-fji31',
     name: 'Georg'
   }];

    const reactTagsProps = {
      /* set the index to the returned string so we can identify later... */
      suggestions: persons.map((person, i) => `${i}. ${person.name}`),

      /* By each addition we get the name-value, just some regex stuff to get the digits at the beginning, voila, we've the index of the suggestion  */
      handleAddition: (person) => {
        const personIndex = /[0-9]*/.exec(person)[0];
        console.log(personIndex);

        /* Now we can get the data from the right choosen person (also if there are people with the same name...  \o/ */
        const selectedPerson = persons[personIndex];

      },
      /* Adapted filter suggestion to ignore the numbers... */
      handleFilterSuggestions: (input, suggestions) => {
        const lowerCaseQuery = input.toLowerCase()
        return suggestions.filter(suggestion => suggestion.toLowerCase().includes(lowerCaseQuery));
      }
    };

    return (
      <div className='person'>
        <ReactTags {...reactTagsProps} />
      </div>
    );
  }
```

<img width="106" alt="screen shot 2016-08-08 at 16 56 48" src="https://cloud.githubusercontent.com/assets/528550/17484201/22564118-5d89-11e6-8616-deb161407517.png">

**Comment by prakhar1989** [comment]
Yeah, I think this is a good way to proceed. You might wanna think about how you want your users to distinguish between same names.
