### ISSUE TITLE
Add Tag Input Button

### ISSUE THREAD

**Issue by steverecio** [prakhar1989/react-tags#612]
Is there a way to add a small button next to the input field that would trigger adding the tag to the list? Or is there a function I can pass to the component to trigger parsing/adding the tag? My users are confused and don't necessarily know that they need to hit Enter or Tab.

**Comment by ad1992** [comment]
@steverecio would you like to give a PR for adding a? submit button ?

**Comment by steverecio** [comment]
I ended up opting for a css tooltip:

```
div.ReactTags__tagInput::after {
    content: "Press ENTER to add tag";
    font-style: italic;
    float: right;
    position: relative;
    bottom: 35px;
    left: 210px;
}
```

**Comment by subodhk01** [comment]
@steverecio but what about mobile devices where there is no enter and the keyboard shows next as an option rather than enter?
