### ISSUE TITLE
dist-modules contains non-ES5 code

### ISSUE THREAD

**Issue by sebinsua** [prakhar1989/react-tags#63]
The contents of `dist-modules` that are used by the module available on NPM [contain non-ES5 code](https://github.com/prakhar1989/react-tags/commit/b7f7152a06825a121ca9f8d3a4d35b58ac1d7269#diff-0cebfb7909e2be875b110504a7fe5755R2). This seems to be a regression that appeared in `2.2.6`.

See the comment here for further clarification: https://github.com/prakhar1989/react-tags/commit/b7f7152a06825a121ca9f8d3a4d35b58ac1d7269#commitcomment-17297357

**Comment by aaronucsd** [comment]
any updates on this? I got the same issue.

```
var { DragDropContext } = require('react-dnd');
    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/longhuynh/Awake/githubs/longh/awakeui-component-taglist/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:357:32)```

**Comment by mike1808** [comment]
To avoid this problem, you can run the latest nods.js with `--harmony_destructuring` argument.

**Comment by prakhar1989** [comment]
Sorry everyone - I've been quite busy which is why this repo has not got a lot of love. I'm working on this now to fix this. Let me know if anyone has ideas on how to proceed!

**Comment by prakhar1989** [comment]
Hey folks, I've published a new version which fixes this. Let me know if you still see something wrong and feel free to re-open this issue. Thanks again for your patience.
