### ISSUE TITLE
v2.2.6 shouldRenderSuggestions renders when query length is smaller

### ISSUE THREAD

**Issue by wiiiim** [prakhar1989/react-tags#65]
Small problem in v2.2.6: 

`    shouldRenderSuggestions: function (query) {
        var props = this.props;
        var minQueryLength = props.minQueryLength || 2;
        return (props.query.length < minQueryLength);
    },`

this renders suggestions when the query length is smaller than minQueryLength, while it should be bigger
this also breaks other things, such as all suggestions showing on the initial state

**Comment by teknologist** [comment]
Exactly!  Crazy bug. Can't even understand how nobody noticed it! :-)

**Comment by klacointe** [comment]
Already noticed here https://github.com/prakhar1989/react-tags/commit/b7f7152a06825a121ca9f8d3a4d35b58ac1d7269#commitcomment-17401576

But no response :confused:

**Comment by teknologist** [comment]
I forked it and fixed it ! :-)

**Comment by wiiiim** [comment]
as a quick fix, you can also just pass your own shouldRenderSuggestions as props

**Comment by prakhar1989** [comment]
Sorry for not getting back on this earlier. This should be fixed now.

**Comment by teknologist** [comment]
Hi @prakhar1989 ,

Shouldn't it be >= ?

I understand it is more a grammar suggestion but IMHO when I say minimum query length is 2 than a query with length 2 should trigger suggestions.

Cheers! :-)

**Comment by prakhar1989** [comment]
Ah damn! You are right! Fix and re-releasing it now. Thanks =)

**Comment by teknologist** [comment]
Thanks! @prakhar1989  :-)
