### ISSUE TITLE
Placeholder is not working

### ISSUE THREAD

**Issue by xumes** [prakhar1989/react-tags#657]
Hello,
I tried to replace the placeholder but it has no effect.

```
<ReactTags
       value={tag}
       tags={tags}
       placeholder="Adicione uma nova Tag"
       suggestions={lista}
       onDelete={(e) => onDelete(e)}
       onAddition={(e) => onAddition(e)}
/>
```

**Comment by mrdannael** [comment]
I've tested in on https://react-tag-input-1nelrc.stackblitz.io and it's working for me with the latest version.

**Comment by xumes** [comment]
Do you mind in show me the snippet you use? When I access this url, I still see the `Add new tag` placeholder. I am developing an app in Portuguese, this is why I need to change it to `Adicione uma nova tag`.
Thanks for the attention.

**Comment by mrdannael** [comment]
Go to the link i've pasted above and try those props:

`<ReactTags
          tags={tags}
          suggestions={suggestions}
          delimiters={delimiters}
          handleDelete={this.handleDelete}
          handleAddition={this.handleAddition}
          handleDrag={this.handleDrag}
          handleTagClick={this.handleTagClick}
          placeholder="Adicione uma nova tag"
        />`
