### ISSUE TITLE
Getting this error on npm install - 5621 error peerinvalid The package react@15.0.2 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by rahulraibit** [prakhar1989/react-tags#67]
I am getting this error. 

5618 error node v4.4.4
5619 error npm  v2.15.1
5620 error code EPEERINVALID
5621 error peerinvalid The package react@15.0.2 does not satisfy its siblings' peerDependencies requirements!
5621 error peerinvalid Peer react-bootstrap@0.29.4 wants react@>=0.14.0
5621 error peerinvalid Peer react-dom@15.0.2 wants react@^15.0.2
5621 error peerinvalid Peer react-redux@4.4.5 wants react@^0.14.0 || ^15.0.0-0
5621 error peerinvalid Peer react-addons-test-utils@15.0.2 wants react@^15.0.2
5621 error peerinvalid Peer react-tag-input@2.2.6 wants react@^0.14.0
5621 error peerinvalid Peer react-dnd@2.1.4 wants react@^0.14.0 || ^15.0.0-0
5621 error peerinvalid Peer react-router@2.4.1 wants react@^0.14.0 || ^15.0.0
5621 error peerinvalid Peer griddle-react@0.5.1 wants react@^0.14.3 || ^15.0.1
5622 verbose exit [ 1, true ]

**Comment by prakhar1989** [comment]
Should be free in v2.2.8. Feel free to re-open issue if this persists.
