### ISSUE TITLE
React 15 Support

### ISSUE THREAD

**Issue by SachaG** [prakhar1989/react-tags#70]
Any plans to switch this package to React 15?

**Comment by prakhar1989** [comment]
Yup! I'll do the migration over tonight (EST) and if all looks good, push a new release (`3.x`) with React 15.

**Comment by SachaG** [comment]
Awesome, thanks so much!

**Comment by prakhar1989** [comment]
Hey @SachaG, I just upgraded to React v15. Give it a try and let me know if you face any issues (I'll keep this issue open until I hear back).

**Comment by SachaG** [comment]
Yep, seems to work just fine! :) http://recordit.co/z1hvGEaWD4 thanks!

**Comment by prakhar1989** [comment]
Fantastic!
