### ISSUE TITLE
v3.0.0 classNames are not applied

### ISSUE THREAD

**Issue by klacointe** [prakhar1989/react-tags#71]
This merge returns always the DefaultClassNames https://github.com/prakhar1989/react-tags/blob/master/lib/reactTags.js#L64

**Comment by prakhar1989** [comment]
Thanks for pointing it out. Seems like an obvious issue - probably lodash changed it's merge API after this was implemented. Fix released in 3.0.1.

**Comment by klacointe** [comment]
Thanks!

NB: You forgot some console.log in the code.

**Comment by prakhar1989** [comment]
Oops. Will remove those in the next release!
