### ISSUE TITLE
make filteredSuggestions settable by user

### ISSUE THREAD

**Issue by facultymatt** [prakhar1989/react-tags#73]
It I have a list of suggestions like so: 

cat
cats
cars
cards

And i start to type

`a`

then I will get a suggestion box with all 4 suggestions and the `a` characters underlined (marked). 

If I then type `ar` 0 suggestions will render. 

It I type `car` then 2 suggestions will render.

I would expect that  any suggestion matching the input pattern would render, not just if the suggestion matches on the first characters.

**Comment by facultymatt** [comment]
I discovered this is because of https://github.com/prakhar1989/react-tags/blob/master/lib/reactTags.js#L81-L85 and maybe other functions which call this.

This behavior makes sense sometimes, but in all cases its not ideal. For example in my case the filtering is done via an API call so my suggestions list is ready to go - the extra filtering step produces unexpected results. 

Is is possible to make this an option so the user can provide their own filter function? What are some other good solutions?

**Comment by facultymatt** [comment]
Noticed that it was easy to override `filteredSuggestions` - would be great to add to the documentation as a supported option 😄

**Comment by prakhar1989** [comment]
Sounds like a good idea. I feel that making the `filter` function, customizable would be useful, but I'm not sure how the API should look like. My understanding is that most users would **not** want to customize that function and hence there should be a reasonable way of making the default available.

I'll see how others are doing it and in the meantime if you have any ideas, feel free to share.
