### ISSUE TITLE
Drag doesn't work when you pre-populate the tag field

### ISSUE THREAD

**Issue by AdamKyle** [prakhar1989/react-tags#79]
![screen shot 2016-06-22 at 2 20 20 pm](https://cloud.githubusercontent.com/assets/188563/16282144/aa127042-3884-11e6-9564-ab96d893abfa.png)

The above is a list of tags to pre populate the tag field:

![screen shot 2016-06-22 at 2 22 12 pm](https://cloud.githubusercontent.com/assets/188563/16282159/c5934562-3884-11e6-9952-ca77c0fca63b.png)

So you can see the tags above. Awesome.

When I try and drag "Bananas" over "Apples", Bananas doesn't switch places, in the console we see:

![screen shot 2016-06-22 at 2 25 06 pm](https://cloud.githubusercontent.com/assets/188563/16282268/3b332bd4-3885-11e6-9510-e94e4c171ae7.png)

You can see that nothing has switched places.

The handle drag function I have is:

```js
  handleDrag(tag, currPos, newPos) {
    var tags = this.state.inputTags;

    // mutate array
    tags.splice(currPos, 1);
    tags.splice(newPos, 0, tag);

    // re-render
    this.setState({ tags: tags });
  }
```

Can you give some guidance on how to get drag to work for pre-filled in tags?

**Comment by ratheous** [comment]
The tags you are pre-populating all have the same ID. Make them unique and it should work.

**Comment by prakhar1989** [comment]
In continuation to what @ratheous has said - have a look at [this](https://github.com/prakhar1989/react-tags/blob/master/example/main.js#L29-L34) example.
