### ISSUE TITLE
component update

### ISSUE THREAD

**Issue by Philin-Anton** [prakhar1989/react-tags#81]
Don't you want to update this component to support ReactJS 15+?

**Comment by prakhar1989** [comment]
It already [does](https://github.com/prakhar1989/react-tags/blob/master/package.json#L25). The README isn't yet updated though. I'll fix that soon enough though.

Thanks for pointing it out!

**Comment by prakhar1989** [comment]
Fixed in https://github.com/prakhar1989/react-tags/commit/bfd74dde3d77de59c605b79fe599d4f80f8071a0

**Comment by Philin-Anton** [comment]
It's cool, thank you!
