### ISSUE TITLE
Handle onBlur event

### ISSUE THREAD

**Issue by Wildhoney** [prakhar1989/react-tags#84]
When you click off of the `input` it would be nice if the value of the `input` had the possibility of being transformed into a tag via the `onblur` event.

I think this is as simple as adding an [`onBlur` to the `input` node](https://github.com/prakhar1989/react-tags/blob/master/lib/reactTags.js#L248-L254) unless anything else needs to occur? We could then accept an optional `handleInputBlur` function via the prop types.

I don't mind adding this myself, but wanted to gather a couple of thoughts first 👍

**Comment by prakhar1989** [comment]
Closing #86
