### ISSUE TITLE
Expose "tag" property to custom remove component.

### ISSUE THREAD

**Issue by ricksuggs** [prakhar1989/react-tags#88]
I'm implementing "strikethrough" tag removal, wherein the user hovers over an existing tag, and the text is styled with `text-decoration: line-through` and upon clicking the text, the tag is removed.

The easiest way to accomplish it is to style css the existing react tags, to not display the real tag text, and update https://github.com/prakhar1989/react-tags/blob/master/lib/Tag.js#L73 to pass in `props.tag`, thereby making it possible to display the tag text in the custom remove component.

```
<span style={{opacity: isDragging ? 0 : 1}} className={props.classNames.tag}>
  {label}
  <RemoveComponent className={props.classNames.remove} onClick={props.onDelete} tag={props.tag} />
</span>
```

```
import React from 'react';

export default class ReactTagStrikethroughRemoveComp extends React.Component {
  render() {
    return (
      <span {...this.props}>
        <span>{this.props.tag.text}</span>
      </span>
    );
  }
}
```

Please let me know if you would like to include this in your library and I will submit a pull request.

Here's the commit on my fork: https://github.com/ricksuggs/react-tags/commit/8583adb33dd9c2108d8810b2c860082e899d6260

Thanks.

**Comment by mrdannael** [comment]
PR #202 should resolve this.
