### ISSUE TITLE
react in dependencies vs peerDependencies

### ISSUE THREAD

**Issue by SachaG** [prakhar1989/react-tags#89]
I noticed that this package lists `react` in `dependencies`, but (at least according to this SO answer) that seems like a bad practice?

http://stackoverflow.com/a/29277601/649299

**Comment by SachaG** [comment]
Another answer saying the same thing: http://stackoverflow.com/a/30454133/649299

FYI moving `react` from `dependencies` to `peerDependencies` fixed the "multiple React" error I was seeing (https://facebook.github.io/react/warnings/refs-must-have-owner.html).

**Comment by prakhar1989** [comment]
Hey @SachaG, you are totally right. I saw what other components are doing, and they too treat it as a peerDepedancy. Thanks for letting me know. I'll make this change and push this up soon.

**Comment by SachaG** [comment]
Awesome 👍

**Comment by prakhar1989** [comment]
Hey @SachaG. Apologies for late turn around - got caught up in some personal stuff. I have released a new version on NPM which react as peer-dependancy. Feel free to re-open the issue if you see any problems with the new release.

Thanks again for letting me know.

**Comment by SachaG** [comment]
Awesome, that's actually a pretty fast turnaround in my book :)
