### ISSUE TITLE
Suggestions only working on the initial tag

### ISSUE THREAD

**Issue by anyati** [prakhar1989/react-tags#90]
I've implemented your library, and I'm trying to make use of the suggestions feature. It seems to work fine for the first tag I input, but once I try to write a second tag, no suggestions pop up. Is this an issue specific to me, or are you experiencing the same issues? Thanks

**Comment by prakhar1989** [comment]
I believe that's an issue specific to you. You can try out a working demo on [WebpackBin](http://www.webpackbin.com/41DVgMvv-)

**Comment by prakhar1989** [comment]
Closing this since I haven't heard back.
