### ISSUE TITLE
Uncaught TypeError: item.toLowerCase is not a function

### ISSUE THREAD

**Issue by ChaimF90** [prakhar1989/react-tags#94]
I am trying to have my app set up so that the suggestions are not hard coded, but rather are tags that I have already saved for this user. When I try to input a tag I get this error: Uncaught TypeError: item.toLowerCase is not a function. What can I do about this?

**Comment by prakhar1989** [comment]
Hi! Thanks for raising the issue. Can you please replicate the issue on [WebpackBin](http://www.webpackbin.com/41DVgMvv-) so that it's easier for us to debug?

**Comment by ChaimF90** [comment]
http://www.webpackbin.com/4JaoQCMK- Here you are.

**Comment by prakhar1989** [comment]
Thanks! So it turns there were two errors in your code.

1. Add `suggestions` in `getInitialState`
```js
 getInitialState: function() {
        return {
            tags: [],
            suggestions: countriesList // need to add a suggestions prop, which was missing
        }
    },
```

2. Correctly pass on the props to the component
```js
 <ReactTags tags={tags}
                    suggestions={suggestions} // this was `tags` earlier but should be suggestions instead
                    handleDelete={this.handleDelete}
                    handleAddition={this.handleAddition}
                    handleDrag={this.handleDrag} />
```

You can see the working version [here](http://www.webpackbin.com/EyWSykXtb). Let me know if that doesn't work.

**Comment by ChaimF90** [comment]
I appreciate your reply, though I am not sure if my initial question was clear. I want to NOT have a separate prop for suggestions, but rather use the tags which are already saved as suggestions. For instance, if this is a user's first time using my site and he does not have any saved tags yet, I would like no suggestions to show up. The next time he comes back to my site, the suggestions will be tags that he already saved. Therefor, I took suggestions away from the constructor and instead passed tags to the suggestions prop.

**Comment by prakhar1989** [comment]
Oh! My apologies for not understanding your question correctly. [Here's](http://www.webpackbin.com/EyWSykXtb) an example of how this could work. 

Basically, you need to change the `handleAddition` function to correctly set the suggestions based on what the user has entered so that the user's entry could serve as suggestions.

**Comment by ChaimF90** [comment]
OK awesome this seems to work. Going to try this in my project now. Thank you!

**Comment by prakhar1989** [comment]
Awesome! I'm closing this issue for now. Feel free to re-open if you get stuck!

**Comment by khushboogupta1** [comment]
@prakhar1989  i got stuck in same issue in **react-native-multiple-tags**
     <MultipleTags
          tags={this.state.allSelectedPubs}
          onChangeItem={(content) => { this.setState({content}); }}
        />
        {
          (() => this.state.content.map(item => <Text key= {item}> {item} </Text>)) ()
        }

      Allselectepubs: 
         "demoTestData"
          "demoTestData1"
HOw can i fix this?
